export declare const listByUser: import("convex/server").RegisteredQuery<"public", {
    status?: "cancelled" | "completed" | "pending" | "confirmed" | undefined;
    page?: number | undefined;
    pageSize?: number | undefined;
    userId: string;
}, Promise<{
    data: {
        _id: import("convex/values").GenericId<"hotelBookings">;
        _creationTime: number;
        status?: "cancelled" | "completed" | "pending" | "confirmed" | undefined;
        latitude?: number | undefined;
        longitude?: number | undefined;
        currency?: string | undefined;
        address?: string | undefined;
        notes?: string | undefined;
        itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
        checkInTime?: string | undefined;
        checkOutTime?: string | undefined;
        roomType?: string | undefined;
        guestCount?: number | undefined;
        totalPrice?: number | undefined;
        pricePerNight?: number | undefined;
        confirmationNumber?: string | undefined;
        bookingPlatform?: string | undefined;
        bookingUrl?: string | undefined;
        hotelPhone?: string | undefined;
        hotelEmail?: string | undefined;
        amenities?: string[] | undefined;
        images?: string[] | undefined;
        importSource?: "email" | "manual" | "import" | undefined;
        rawEmailContent?: string | undefined;
        userId: string;
        hotelName: string;
        checkInDate: string;
        checkOutDate: string;
        roomCount: number;
    }[];
    total: number;
}>>;
export declare const listByItinerary: import("convex/server").RegisteredQuery<"public", {
    itineraryId: import("convex/values").GenericId<"itineraries">;
}, Promise<{
    _id: import("convex/values").GenericId<"hotelBookings">;
    _creationTime: number;
    status?: "cancelled" | "completed" | "pending" | "confirmed" | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    currency?: string | undefined;
    address?: string | undefined;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    checkInTime?: string | undefined;
    checkOutTime?: string | undefined;
    roomType?: string | undefined;
    guestCount?: number | undefined;
    totalPrice?: number | undefined;
    pricePerNight?: number | undefined;
    confirmationNumber?: string | undefined;
    bookingPlatform?: string | undefined;
    bookingUrl?: string | undefined;
    hotelPhone?: string | undefined;
    hotelEmail?: string | undefined;
    amenities?: string[] | undefined;
    images?: string[] | undefined;
    importSource?: "email" | "manual" | "import" | undefined;
    rawEmailContent?: string | undefined;
    userId: string;
    hotelName: string;
    checkInDate: string;
    checkOutDate: string;
    roomCount: number;
}[]>>;
export declare const getById: import("convex/server").RegisteredQuery<"public", {
    id: import("convex/values").GenericId<"hotelBookings">;
}, Promise<{
    _id: import("convex/values").GenericId<"hotelBookings">;
    _creationTime: number;
    status?: "cancelled" | "completed" | "pending" | "confirmed" | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    currency?: string | undefined;
    address?: string | undefined;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    checkInTime?: string | undefined;
    checkOutTime?: string | undefined;
    roomType?: string | undefined;
    guestCount?: number | undefined;
    totalPrice?: number | undefined;
    pricePerNight?: number | undefined;
    confirmationNumber?: string | undefined;
    bookingPlatform?: string | undefined;
    bookingUrl?: string | undefined;
    hotelPhone?: string | undefined;
    hotelEmail?: string | undefined;
    amenities?: string[] | undefined;
    images?: string[] | undefined;
    importSource?: "email" | "manual" | "import" | undefined;
    rawEmailContent?: string | undefined;
    userId: string;
    hotelName: string;
    checkInDate: string;
    checkOutDate: string;
    roomCount: number;
} | null>>;
export declare const getUpcoming: import("convex/server").RegisteredQuery<"public", {
    limit?: number | undefined;
    userId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"hotelBookings">;
    _creationTime: number;
    status?: "cancelled" | "completed" | "pending" | "confirmed" | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    currency?: string | undefined;
    address?: string | undefined;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    checkInTime?: string | undefined;
    checkOutTime?: string | undefined;
    roomType?: string | undefined;
    guestCount?: number | undefined;
    totalPrice?: number | undefined;
    pricePerNight?: number | undefined;
    confirmationNumber?: string | undefined;
    bookingPlatform?: string | undefined;
    bookingUrl?: string | undefined;
    hotelPhone?: string | undefined;
    hotelEmail?: string | undefined;
    amenities?: string[] | undefined;
    images?: string[] | undefined;
    importSource?: "email" | "manual" | "import" | undefined;
    rawEmailContent?: string | undefined;
    userId: string;
    hotelName: string;
    checkInDate: string;
    checkOutDate: string;
    roomCount: number;
}[]>>;
export declare const create: import("convex/server").RegisteredMutation<"public", {
    status?: "cancelled" | "completed" | "pending" | "confirmed" | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    currency?: string | undefined;
    address?: string | undefined;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    checkInTime?: string | undefined;
    checkOutTime?: string | undefined;
    roomType?: string | undefined;
    guestCount?: number | undefined;
    totalPrice?: number | undefined;
    pricePerNight?: number | undefined;
    confirmationNumber?: string | undefined;
    bookingPlatform?: string | undefined;
    bookingUrl?: string | undefined;
    hotelPhone?: string | undefined;
    hotelEmail?: string | undefined;
    amenities?: string[] | undefined;
    images?: string[] | undefined;
    importSource?: "email" | "manual" | "import" | undefined;
    rawEmailContent?: string | undefined;
    userId: string;
    hotelName: string;
    checkInDate: string;
    checkOutDate: string;
    roomCount: number;
}, Promise<import("convex/values").GenericId<"hotelBookings">>>;
export declare const update: import("convex/server").RegisteredMutation<"public", {
    status?: "cancelled" | "completed" | "pending" | "confirmed" | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    currency?: string | undefined;
    address?: string | undefined;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    hotelName?: string | undefined;
    checkInDate?: string | undefined;
    checkOutDate?: string | undefined;
    checkInTime?: string | undefined;
    checkOutTime?: string | undefined;
    roomType?: string | undefined;
    roomCount?: number | undefined;
    guestCount?: number | undefined;
    totalPrice?: number | undefined;
    pricePerNight?: number | undefined;
    confirmationNumber?: string | undefined;
    bookingPlatform?: string | undefined;
    bookingUrl?: string | undefined;
    hotelPhone?: string | undefined;
    hotelEmail?: string | undefined;
    amenities?: string[] | undefined;
    images?: string[] | undefined;
    id: import("convex/values").GenericId<"hotelBookings">;
    userId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"hotelBookings">;
    _creationTime: number;
    status?: "cancelled" | "completed" | "pending" | "confirmed" | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    currency?: string | undefined;
    address?: string | undefined;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    checkInTime?: string | undefined;
    checkOutTime?: string | undefined;
    roomType?: string | undefined;
    guestCount?: number | undefined;
    totalPrice?: number | undefined;
    pricePerNight?: number | undefined;
    confirmationNumber?: string | undefined;
    bookingPlatform?: string | undefined;
    bookingUrl?: string | undefined;
    hotelPhone?: string | undefined;
    hotelEmail?: string | undefined;
    amenities?: string[] | undefined;
    images?: string[] | undefined;
    importSource?: "email" | "manual" | "import" | undefined;
    rawEmailContent?: string | undefined;
    userId: string;
    hotelName: string;
    checkInDate: string;
    checkOutDate: string;
    roomCount: number;
} | null>>;
export declare const remove: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"hotelBookings">;
    userId: string;
}, Promise<void>>;
export declare const linkToItinerary: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"hotelBookings">;
    userId: string;
    itineraryId: import("convex/values").GenericId<"itineraries">;
}, Promise<{
    _id: import("convex/values").GenericId<"hotelBookings">;
    _creationTime: number;
    status?: "cancelled" | "completed" | "pending" | "confirmed" | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    currency?: string | undefined;
    address?: string | undefined;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    checkInTime?: string | undefined;
    checkOutTime?: string | undefined;
    roomType?: string | undefined;
    guestCount?: number | undefined;
    totalPrice?: number | undefined;
    pricePerNight?: number | undefined;
    confirmationNumber?: string | undefined;
    bookingPlatform?: string | undefined;
    bookingUrl?: string | undefined;
    hotelPhone?: string | undefined;
    hotelEmail?: string | undefined;
    amenities?: string[] | undefined;
    images?: string[] | undefined;
    importSource?: "email" | "manual" | "import" | undefined;
    rawEmailContent?: string | undefined;
    userId: string;
    hotelName: string;
    checkInDate: string;
    checkOutDate: string;
    roomCount: number;
} | null>>;
export declare const unlinkFromItinerary: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"hotelBookings">;
    userId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"hotelBookings">;
    _creationTime: number;
    status?: "cancelled" | "completed" | "pending" | "confirmed" | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    currency?: string | undefined;
    address?: string | undefined;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    checkInTime?: string | undefined;
    checkOutTime?: string | undefined;
    roomType?: string | undefined;
    guestCount?: number | undefined;
    totalPrice?: number | undefined;
    pricePerNight?: number | undefined;
    confirmationNumber?: string | undefined;
    bookingPlatform?: string | undefined;
    bookingUrl?: string | undefined;
    hotelPhone?: string | undefined;
    hotelEmail?: string | undefined;
    amenities?: string[] | undefined;
    images?: string[] | undefined;
    importSource?: "email" | "manual" | "import" | undefined;
    rawEmailContent?: string | undefined;
    userId: string;
    hotelName: string;
    checkInDate: string;
    checkOutDate: string;
    roomCount: number;
} | null>>;
export declare const updateStatus: import("convex/server").RegisteredMutation<"public", {
    status: "cancelled" | "completed" | "pending" | "confirmed";
    id: import("convex/values").GenericId<"hotelBookings">;
    userId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"hotelBookings">;
    _creationTime: number;
    status?: "cancelled" | "completed" | "pending" | "confirmed" | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    currency?: string | undefined;
    address?: string | undefined;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    checkInTime?: string | undefined;
    checkOutTime?: string | undefined;
    roomType?: string | undefined;
    guestCount?: number | undefined;
    totalPrice?: number | undefined;
    pricePerNight?: number | undefined;
    confirmationNumber?: string | undefined;
    bookingPlatform?: string | undefined;
    bookingUrl?: string | undefined;
    hotelPhone?: string | undefined;
    hotelEmail?: string | undefined;
    amenities?: string[] | undefined;
    images?: string[] | undefined;
    importSource?: "email" | "manual" | "import" | undefined;
    rawEmailContent?: string | undefined;
    userId: string;
    hotelName: string;
    checkInDate: string;
    checkOutDate: string;
    roomCount: number;
} | null>>;
export declare const parseEmailContent: import("convex/server").RegisteredMutation<"public", {
    userId: string;
    emailContent: string;
}, Promise<{
    bookingId: import("convex/values").GenericId<"hotelBookings">;
    needsManualReview: boolean;
    message: string;
}>>;
export declare const calculateNights: import("convex/server").RegisteredQuery<"public", {
    checkInDate: string;
    checkOutDate: string;
}, Promise<number>>;
