/**
 * Safety - Destination Safety Ratings, Alerts, and Danger Zones
 */
export declare const getSafetyRating: import("convex/server").RegisteredQuery<"public", {
    countryCode?: string | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    destinationName?: string | undefined;
}, Promise<{
    _id: import("convex/values").GenericId<"safetyRatings">;
    _creationTime: number;
    sourceUrl?: string | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    verifiedBy?: string | undefined;
    destinationNameEn?: string | undefined;
    womenSafetyRating?: number | undefined;
    lgbtqSafetyRating?: number | undefined;
    summaryEn?: string | undefined;
    emergencyNumbers?: {
        touristHotline?: string | undefined;
        police?: string | undefined;
        ambulance?: string | undefined;
        fire?: string | undefined;
    } | undefined;
    createdAt: number;
    summary: string;
    updatedAt: number;
    countryCode: string;
    source: string;
    destinationName: string;
    overallRating: number;
    crimeRating: number;
    healthRating: number;
    naturalDisasterRating: number;
    transportRating: number;
    generalTips: string[];
    lastVerifiedAt: number;
} | null>>;
export declare const listSafetyRatingsByCountry: import("convex/server").RegisteredQuery<"public", {
    limit?: number | undefined;
    countryCode: string;
}, Promise<{
    _id: import("convex/values").GenericId<"safetyRatings">;
    _creationTime: number;
    sourceUrl?: string | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    verifiedBy?: string | undefined;
    destinationNameEn?: string | undefined;
    womenSafetyRating?: number | undefined;
    lgbtqSafetyRating?: number | undefined;
    summaryEn?: string | undefined;
    emergencyNumbers?: {
        touristHotline?: string | undefined;
        police?: string | undefined;
        ambulance?: string | undefined;
        fire?: string | undefined;
    } | undefined;
    createdAt: number;
    summary: string;
    updatedAt: number;
    countryCode: string;
    source: string;
    destinationName: string;
    overallRating: number;
    crimeRating: number;
    healthRating: number;
    naturalDisasterRating: number;
    transportRating: number;
    generalTips: string[];
    lastVerifiedAt: number;
}[]>>;
export declare const listSafestDestinations: import("convex/server").RegisteredQuery<"public", {
    limit?: number | undefined;
    minRating?: number | undefined;
}, Promise<{
    _id: import("convex/values").GenericId<"safetyRatings">;
    _creationTime: number;
    sourceUrl?: string | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    verifiedBy?: string | undefined;
    destinationNameEn?: string | undefined;
    womenSafetyRating?: number | undefined;
    lgbtqSafetyRating?: number | undefined;
    summaryEn?: string | undefined;
    emergencyNumbers?: {
        touristHotline?: string | undefined;
        police?: string | undefined;
        ambulance?: string | undefined;
        fire?: string | undefined;
    } | undefined;
    createdAt: number;
    summary: string;
    updatedAt: number;
    countryCode: string;
    source: string;
    destinationName: string;
    overallRating: number;
    crimeRating: number;
    healthRating: number;
    naturalDisasterRating: number;
    transportRating: number;
    generalTips: string[];
    lastVerifiedAt: number;
}[]>>;
export declare const upsertSafetyRating: import("convex/server").RegisteredMutation<"public", {
    sourceUrl?: string | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    verifiedBy?: string | undefined;
    destinationNameEn?: string | undefined;
    womenSafetyRating?: number | undefined;
    lgbtqSafetyRating?: number | undefined;
    summaryEn?: string | undefined;
    emergencyNumbers?: {
        touristHotline?: string | undefined;
        police?: string | undefined;
        ambulance?: string | undefined;
        fire?: string | undefined;
    } | undefined;
    summary: string;
    countryCode: string;
    source: string;
    destinationName: string;
    overallRating: number;
    crimeRating: number;
    healthRating: number;
    naturalDisasterRating: number;
    transportRating: number;
    generalTips: string[];
}, Promise<import("convex/values").GenericId<"safetyRatings">>>;
export declare const getActiveAlerts: import("convex/server").RegisteredQuery<"public", {
    countryCode?: string | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    alertType?: "other" | "travel_advisory" | "health_warning" | "natural_disaster" | "civil_unrest" | "terrorism" | "crime_spike" | "scam_warning" | undefined;
    destinationName?: string | undefined;
    severity?: "info" | "critical" | "low" | "medium" | "high" | undefined;
}, Promise<{
    _id: import("convex/values").GenericId<"safetyAlerts">;
    _creationTime: number;
    sourceUrl?: string | undefined;
    endDate?: number | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    descriptionEn?: string | undefined;
    titleEn?: string | undefined;
    affectedAreas?: string[] | undefined;
    avoidAreas?: string[] | undefined;
    officialAdvisoryLevel?: string | undefined;
    createdBy?: string | undefined;
    createdAt: number;
    description: string;
    title: string;
    startDate: number;
    updatedAt: number;
    countryCode: string;
    source: string;
    isActive: boolean;
    alertType: "other" | "travel_advisory" | "health_warning" | "natural_disaster" | "civil_unrest" | "terrorism" | "crime_spike" | "scam_warning";
    destinationName: string;
    severity: "info" | "critical" | "low" | "medium" | "high";
    recommendations: string[];
}[]>>;
export declare const getAlertById: import("convex/server").RegisteredQuery<"public", {
    id: import("convex/values").GenericId<"safetyAlerts">;
}, Promise<{
    _id: import("convex/values").GenericId<"safetyAlerts">;
    _creationTime: number;
    sourceUrl?: string | undefined;
    endDate?: number | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    descriptionEn?: string | undefined;
    titleEn?: string | undefined;
    affectedAreas?: string[] | undefined;
    avoidAreas?: string[] | undefined;
    officialAdvisoryLevel?: string | undefined;
    createdBy?: string | undefined;
    createdAt: number;
    description: string;
    title: string;
    startDate: number;
    updatedAt: number;
    countryCode: string;
    source: string;
    isActive: boolean;
    alertType: "other" | "travel_advisory" | "health_warning" | "natural_disaster" | "civil_unrest" | "terrorism" | "crime_spike" | "scam_warning";
    destinationName: string;
    severity: "info" | "critical" | "low" | "medium" | "high";
    recommendations: string[];
} | null>>;
export declare const createAlert: import("convex/server").RegisteredMutation<"public", {
    sourceUrl?: string | undefined;
    endDate?: number | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    descriptionEn?: string | undefined;
    titleEn?: string | undefined;
    affectedAreas?: string[] | undefined;
    avoidAreas?: string[] | undefined;
    officialAdvisoryLevel?: string | undefined;
    createdBy?: string | undefined;
    description: string;
    title: string;
    startDate: number;
    countryCode: string;
    source: string;
    alertType: "other" | "travel_advisory" | "health_warning" | "natural_disaster" | "civil_unrest" | "terrorism" | "crime_spike" | "scam_warning";
    destinationName: string;
    severity: "info" | "critical" | "low" | "medium" | "high";
    recommendations: string[];
}, Promise<import("convex/values").GenericId<"safetyAlerts">>>;
export declare const updateAlert: import("convex/server").RegisteredMutation<"public", {
    description?: string | undefined;
    title?: string | undefined;
    endDate?: number | undefined;
    descriptionEn?: string | undefined;
    titleEn?: string | undefined;
    isActive?: boolean | undefined;
    severity?: "info" | "critical" | "low" | "medium" | "high" | undefined;
    recommendations?: string[] | undefined;
    avoidAreas?: string[] | undefined;
    id: import("convex/values").GenericId<"safetyAlerts">;
}, Promise<{
    _id: import("convex/values").GenericId<"safetyAlerts">;
    _creationTime: number;
    sourceUrl?: string | undefined;
    endDate?: number | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    descriptionEn?: string | undefined;
    titleEn?: string | undefined;
    affectedAreas?: string[] | undefined;
    avoidAreas?: string[] | undefined;
    officialAdvisoryLevel?: string | undefined;
    createdBy?: string | undefined;
    createdAt: number;
    description: string;
    title: string;
    startDate: number;
    updatedAt: number;
    countryCode: string;
    source: string;
    isActive: boolean;
    alertType: "other" | "travel_advisory" | "health_warning" | "natural_disaster" | "civil_unrest" | "terrorism" | "crime_spike" | "scam_warning";
    destinationName: string;
    severity: "info" | "critical" | "low" | "medium" | "high";
    recommendations: string[];
} | null>>;
export declare const deactivateAlert: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"safetyAlerts">;
}, Promise<void>>;
export declare const getDangerZones: import("convex/server").RegisteredQuery<"public", {
    countryCode?: string | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    destinationName?: string | undefined;
    dangerLevel?: "caution" | "avoid_night" | "avoid_alone" | "high_risk" | "no_go" | undefined;
    activeOnly?: boolean | undefined;
}, Promise<{
    _id: import("convex/values").GenericId<"dangerZones">;
    _creationTime: number;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    descriptionEn?: string | undefined;
    verifiedBy?: string | undefined;
    zoneNameEn?: string | undefined;
    radiusMeters?: number | undefined;
    polygon?: {
        lat: number;
        lng: number;
    }[] | undefined;
    dangerousTimes?: {
        nightOnly?: boolean | undefined;
        specificHours?: string | undefined;
        specificDays?: string[] | undefined;
        allDay: boolean;
    } | undefined;
    lastReportedAt?: number | undefined;
    createdAt: number;
    description: string;
    latitude: number;
    longitude: number;
    updatedAt: number;
    countryCode: string;
    source: string;
    isActive: boolean;
    reportCount: number;
    destinationName: string;
    zoneName: string;
    dangerLevel: "caution" | "avoid_night" | "avoid_alone" | "high_risk" | "no_go";
    dangerTypes: ("other" | "crime" | "scam" | "traffic" | "natural_hazard" | "political" | "health")[];
    precautions: string[];
    isVerified: boolean;
}[]>>;
export declare const getNearbyDangerZones: import("convex/server").RegisteredQuery<"public", {
    activeOnly?: boolean | undefined;
    latitude: number;
    longitude: number;
    radiusKm: number;
}, Promise<{
    distance: number;
    _id: import("convex/values").GenericId<"dangerZones">;
    _creationTime: number;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    descriptionEn?: string | undefined;
    verifiedBy?: string | undefined;
    zoneNameEn?: string | undefined;
    radiusMeters?: number | undefined;
    polygon?: {
        lat: number;
        lng: number;
    }[] | undefined;
    dangerousTimes?: {
        nightOnly?: boolean | undefined;
        specificHours?: string | undefined;
        specificDays?: string[] | undefined;
        allDay: boolean;
    } | undefined;
    lastReportedAt?: number | undefined;
    createdAt: number;
    description: string;
    latitude: number;
    longitude: number;
    updatedAt: number;
    countryCode: string;
    source: string;
    isActive: boolean;
    reportCount: number;
    destinationName: string;
    zoneName: string;
    dangerLevel: "caution" | "avoid_night" | "avoid_alone" | "high_risk" | "no_go";
    dangerTypes: ("other" | "crime" | "scam" | "traffic" | "natural_hazard" | "political" | "health")[];
    precautions: string[];
    isVerified: boolean;
}[]>>;
export declare const createDangerZone: import("convex/server").RegisteredMutation<"public", {
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    descriptionEn?: string | undefined;
    zoneNameEn?: string | undefined;
    radiusMeters?: number | undefined;
    polygon?: {
        lat: number;
        lng: number;
    }[] | undefined;
    dangerousTimes?: {
        nightOnly?: boolean | undefined;
        specificHours?: string | undefined;
        specificDays?: string[] | undefined;
        allDay: boolean;
    } | undefined;
    description: string;
    latitude: number;
    longitude: number;
    countryCode: string;
    source: string;
    destinationName: string;
    zoneName: string;
    dangerLevel: "caution" | "avoid_night" | "avoid_alone" | "high_risk" | "no_go";
    dangerTypes: ("other" | "crime" | "scam" | "traffic" | "natural_hazard" | "political" | "health")[];
    precautions: string[];
}, Promise<import("convex/values").GenericId<"dangerZones">>>;
export declare const updateDangerZone: import("convex/server").RegisteredMutation<"public", {
    description?: string | undefined;
    descriptionEn?: string | undefined;
    isActive?: boolean | undefined;
    verifiedBy?: string | undefined;
    zoneName?: string | undefined;
    zoneNameEn?: string | undefined;
    dangerLevel?: "caution" | "avoid_night" | "avoid_alone" | "high_risk" | "no_go" | undefined;
    dangerTypes?: ("other" | "crime" | "scam" | "traffic" | "natural_hazard" | "political" | "health")[] | undefined;
    precautions?: string[] | undefined;
    isVerified?: boolean | undefined;
    id: import("convex/values").GenericId<"dangerZones">;
}, Promise<{
    _id: import("convex/values").GenericId<"dangerZones">;
    _creationTime: number;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    descriptionEn?: string | undefined;
    verifiedBy?: string | undefined;
    zoneNameEn?: string | undefined;
    radiusMeters?: number | undefined;
    polygon?: {
        lat: number;
        lng: number;
    }[] | undefined;
    dangerousTimes?: {
        nightOnly?: boolean | undefined;
        specificHours?: string | undefined;
        specificDays?: string[] | undefined;
        allDay: boolean;
    } | undefined;
    lastReportedAt?: number | undefined;
    createdAt: number;
    description: string;
    latitude: number;
    longitude: number;
    updatedAt: number;
    countryCode: string;
    source: string;
    isActive: boolean;
    reportCount: number;
    destinationName: string;
    zoneName: string;
    dangerLevel: "caution" | "avoid_night" | "avoid_alone" | "high_risk" | "no_go";
    dangerTypes: ("other" | "crime" | "scam" | "traffic" | "natural_hazard" | "political" | "health")[];
    precautions: string[];
    isVerified: boolean;
} | null>>;
export declare const getIncidentReports: import("convex/server").RegisteredQuery<"public", {
    status?: "rejected" | "pending" | "resolved" | "verified" | undefined;
    limit?: number | undefined;
    countryCode?: string | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    destinationName?: string | undefined;
    incidentType?: "other" | "harassment" | "natural_disaster" | "scam" | "theft" | "assault" | "traffic_accident" | "health_issue" | "police_issue" | undefined;
}, Promise<{
    _id: import("convex/values").GenericId<"safetyIncidentReports">;
    _creationTime: number;
    latitude?: number | undefined;
    longitude?: number | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    moderatorNotes?: string | undefined;
    reviewedBy?: string | undefined;
    reviewedAt?: number | undefined;
    specificLocation?: string | undefined;
    wasPoliceInvolved?: boolean | undefined;
    wasResolved?: boolean | undefined;
    resolutionNotes?: string | undefined;
    status: "rejected" | "pending" | "resolved" | "verified";
    createdAt: number;
    description: string;
    title: string;
    userId: string;
    updatedAt: number;
    countryCode: string;
    reportCount: number;
    destinationName: string;
    severity: "critical" | "moderate" | "minor" | "severe";
    helpfulCount: number;
    isAnonymous: boolean;
    incidentType: "other" | "harassment" | "natural_disaster" | "scam" | "theft" | "assault" | "traffic_accident" | "health_issue" | "police_issue";
    incidentDate: number;
}[]>>;
export declare const getUserIncidentReports: import("convex/server").RegisteredQuery<"public", {
    limit?: number | undefined;
    userId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"safetyIncidentReports">;
    _creationTime: number;
    latitude?: number | undefined;
    longitude?: number | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    moderatorNotes?: string | undefined;
    reviewedBy?: string | undefined;
    reviewedAt?: number | undefined;
    specificLocation?: string | undefined;
    wasPoliceInvolved?: boolean | undefined;
    wasResolved?: boolean | undefined;
    resolutionNotes?: string | undefined;
    status: "rejected" | "pending" | "resolved" | "verified";
    createdAt: number;
    description: string;
    title: string;
    userId: string;
    updatedAt: number;
    countryCode: string;
    reportCount: number;
    destinationName: string;
    severity: "critical" | "moderate" | "minor" | "severe";
    helpfulCount: number;
    isAnonymous: boolean;
    incidentType: "other" | "harassment" | "natural_disaster" | "scam" | "theft" | "assault" | "traffic_accident" | "health_issue" | "police_issue";
    incidentDate: number;
}[]>>;
export declare const createIncidentReport: import("convex/server").RegisteredMutation<"public", {
    latitude?: number | undefined;
    longitude?: number | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    specificLocation?: string | undefined;
    wasPoliceInvolved?: boolean | undefined;
    wasResolved?: boolean | undefined;
    resolutionNotes?: string | undefined;
    description: string;
    title: string;
    userId: string;
    countryCode: string;
    destinationName: string;
    severity: "critical" | "moderate" | "minor" | "severe";
    isAnonymous: boolean;
    incidentType: "other" | "harassment" | "natural_disaster" | "scam" | "theft" | "assault" | "traffic_accident" | "health_issue" | "police_issue";
    incidentDate: number;
}, Promise<import("convex/values").GenericId<"safetyIncidentReports">>>;
export declare const markReportHelpful: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"safetyIncidentReports">;
}, Promise<void>>;
export declare const moderateIncidentReport: import("convex/server").RegisteredMutation<"public", {
    moderatorNotes?: string | undefined;
    status: "rejected" | "pending" | "resolved" | "verified";
    id: import("convex/values").GenericId<"safetyIncidentReports">;
    reviewedBy: string;
}, Promise<{
    _id: import("convex/values").GenericId<"safetyIncidentReports">;
    _creationTime: number;
    latitude?: number | undefined;
    longitude?: number | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    moderatorNotes?: string | undefined;
    reviewedBy?: string | undefined;
    reviewedAt?: number | undefined;
    specificLocation?: string | undefined;
    wasPoliceInvolved?: boolean | undefined;
    wasResolved?: boolean | undefined;
    resolutionNotes?: string | undefined;
    status: "rejected" | "pending" | "resolved" | "verified";
    createdAt: number;
    description: string;
    title: string;
    userId: string;
    updatedAt: number;
    countryCode: string;
    reportCount: number;
    destinationName: string;
    severity: "critical" | "moderate" | "minor" | "severe";
    helpfulCount: number;
    isAnonymous: boolean;
    incidentType: "other" | "harassment" | "natural_disaster" | "scam" | "theft" | "assault" | "traffic_accident" | "health_issue" | "police_issue";
    incidentDate: number;
} | null>>;
export declare const getDestinationSafetyInfo: import("convex/server").RegisteredQuery<"public", {
    countryCode?: string | undefined;
    destinationName: string;
}, Promise<{
    rating: {
        _id: import("convex/values").GenericId<"safetyRatings">;
        _creationTime: number;
        sourceUrl?: string | undefined;
        cityId?: import("convex/values").GenericId<"cities"> | undefined;
        verifiedBy?: string | undefined;
        destinationNameEn?: string | undefined;
        womenSafetyRating?: number | undefined;
        lgbtqSafetyRating?: number | undefined;
        summaryEn?: string | undefined;
        emergencyNumbers?: {
            touristHotline?: string | undefined;
            police?: string | undefined;
            ambulance?: string | undefined;
            fire?: string | undefined;
        } | undefined;
        createdAt: number;
        summary: string;
        updatedAt: number;
        countryCode: string;
        source: string;
        destinationName: string;
        overallRating: number;
        crimeRating: number;
        healthRating: number;
        naturalDisasterRating: number;
        transportRating: number;
        generalTips: string[];
        lastVerifiedAt: number;
    } | null;
    alerts: {
        _id: import("convex/values").GenericId<"safetyAlerts">;
        _creationTime: number;
        sourceUrl?: string | undefined;
        endDate?: number | undefined;
        cityId?: import("convex/values").GenericId<"cities"> | undefined;
        descriptionEn?: string | undefined;
        titleEn?: string | undefined;
        affectedAreas?: string[] | undefined;
        avoidAreas?: string[] | undefined;
        officialAdvisoryLevel?: string | undefined;
        createdBy?: string | undefined;
        createdAt: number;
        description: string;
        title: string;
        startDate: number;
        updatedAt: number;
        countryCode: string;
        source: string;
        isActive: boolean;
        alertType: "other" | "travel_advisory" | "health_warning" | "natural_disaster" | "civil_unrest" | "terrorism" | "crime_spike" | "scam_warning";
        destinationName: string;
        severity: "info" | "critical" | "low" | "medium" | "high";
        recommendations: string[];
    }[];
    dangerZones: {
        _id: import("convex/values").GenericId<"dangerZones">;
        _creationTime: number;
        cityId?: import("convex/values").GenericId<"cities"> | undefined;
        descriptionEn?: string | undefined;
        verifiedBy?: string | undefined;
        zoneNameEn?: string | undefined;
        radiusMeters?: number | undefined;
        polygon?: {
            lat: number;
            lng: number;
        }[] | undefined;
        dangerousTimes?: {
            nightOnly?: boolean | undefined;
            specificHours?: string | undefined;
            specificDays?: string[] | undefined;
            allDay: boolean;
        } | undefined;
        lastReportedAt?: number | undefined;
        createdAt: number;
        description: string;
        latitude: number;
        longitude: number;
        updatedAt: number;
        countryCode: string;
        source: string;
        isActive: boolean;
        reportCount: number;
        destinationName: string;
        zoneName: string;
        dangerLevel: "caution" | "avoid_night" | "avoid_alone" | "high_risk" | "no_go";
        dangerTypes: ("other" | "crime" | "scam" | "traffic" | "natural_hazard" | "political" | "health")[];
        precautions: string[];
        isVerified: boolean;
    }[];
    recentIncidents: {
        _id: import("convex/values").GenericId<"safetyIncidentReports">;
        _creationTime: number;
        latitude?: number | undefined;
        longitude?: number | undefined;
        cityId?: import("convex/values").GenericId<"cities"> | undefined;
        moderatorNotes?: string | undefined;
        reviewedBy?: string | undefined;
        reviewedAt?: number | undefined;
        specificLocation?: string | undefined;
        wasPoliceInvolved?: boolean | undefined;
        wasResolved?: boolean | undefined;
        resolutionNotes?: string | undefined;
        status: "rejected" | "pending" | "resolved" | "verified";
        createdAt: number;
        description: string;
        title: string;
        userId: string;
        updatedAt: number;
        countryCode: string;
        reportCount: number;
        destinationName: string;
        severity: "critical" | "moderate" | "minor" | "severe";
        helpfulCount: number;
        isAnonymous: boolean;
        incidentType: "other" | "harassment" | "natural_disaster" | "scam" | "theft" | "assault" | "traffic_accident" | "health_issue" | "police_issue";
        incidentDate: number;
    }[];
    hasActiveAlerts: boolean;
    hasCriticalAlerts: boolean;
    dangerZoneCount: number;
}>>;
