export declare const listBySimCard: import("convex/server").RegisteredQuery<"public", {
    status?: "approved" | "rejected" | "pending" | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
    simCardId: import("convex/values").GenericId<"simCards">;
}, Promise<{
    _id: import("convex/values").GenericId<"simCardReviews">;
    _creationTime: number;
    title?: string | undefined;
    destination?: string | undefined;
    userId?: string | undefined;
    updatedAt?: number | undefined;
    imageUrls?: string[] | undefined;
    authorName?: string | undefined;
    speedRating?: number | undefined;
    speedTestResult?: string | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    signalRating?: number | undefined;
    valueRating?: number | undefined;
    serviceRating?: number | undefined;
    usageDuration?: number | undefined;
    actualDataUsed?: string | undefined;
    deviceUsed?: string | undefined;
    activationExperience?: string | undefined;
    signalQuality?: "excellent" | "good" | "average" | "poor" | "very_poor" | undefined;
    purchaseVerified?: boolean | undefined;
    reviewDate?: number | undefined;
    status: "approved" | "rejected" | "pending";
    content: string;
    createdAt: number;
    wouldRecommend: boolean;
    reportCount: number;
    overallRating: number;
    isVerified: boolean;
    helpfulCount: number;
    simCardId: import("convex/values").GenericId<"simCards">;
}[]>>;
export declare const listByUser: import("convex/server").RegisteredQuery<"public", {
    limit?: number | undefined;
    userId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"simCardReviews">;
    _creationTime: number;
    title?: string | undefined;
    destination?: string | undefined;
    userId?: string | undefined;
    updatedAt?: number | undefined;
    imageUrls?: string[] | undefined;
    authorName?: string | undefined;
    speedRating?: number | undefined;
    speedTestResult?: string | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    signalRating?: number | undefined;
    valueRating?: number | undefined;
    serviceRating?: number | undefined;
    usageDuration?: number | undefined;
    actualDataUsed?: string | undefined;
    deviceUsed?: string | undefined;
    activationExperience?: string | undefined;
    signalQuality?: "excellent" | "good" | "average" | "poor" | "very_poor" | undefined;
    purchaseVerified?: boolean | undefined;
    reviewDate?: number | undefined;
    status: "approved" | "rejected" | "pending";
    content: string;
    createdAt: number;
    wouldRecommend: boolean;
    reportCount: number;
    overallRating: number;
    isVerified: boolean;
    helpfulCount: number;
    simCardId: import("convex/values").GenericId<"simCards">;
}[]>>;
export declare const getById: import("convex/server").RegisteredQuery<"public", {
    id: import("convex/values").GenericId<"simCardReviews">;
}, Promise<{
    _id: import("convex/values").GenericId<"simCardReviews">;
    _creationTime: number;
    title?: string | undefined;
    destination?: string | undefined;
    userId?: string | undefined;
    updatedAt?: number | undefined;
    imageUrls?: string[] | undefined;
    authorName?: string | undefined;
    speedRating?: number | undefined;
    speedTestResult?: string | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    signalRating?: number | undefined;
    valueRating?: number | undefined;
    serviceRating?: number | undefined;
    usageDuration?: number | undefined;
    actualDataUsed?: string | undefined;
    deviceUsed?: string | undefined;
    activationExperience?: string | undefined;
    signalQuality?: "excellent" | "good" | "average" | "poor" | "very_poor" | undefined;
    purchaseVerified?: boolean | undefined;
    reviewDate?: number | undefined;
    status: "approved" | "rejected" | "pending";
    content: string;
    createdAt: number;
    wouldRecommend: boolean;
    reportCount: number;
    overallRating: number;
    isVerified: boolean;
    helpfulCount: number;
    simCardId: import("convex/values").GenericId<"simCards">;
} | null>>;
export declare const getUserReview: import("convex/server").RegisteredQuery<"public", {
    userId: string;
    simCardId: import("convex/values").GenericId<"simCards">;
}, Promise<{
    _id: import("convex/values").GenericId<"simCardReviews">;
    _creationTime: number;
    title?: string | undefined;
    destination?: string | undefined;
    userId?: string | undefined;
    updatedAt?: number | undefined;
    imageUrls?: string[] | undefined;
    authorName?: string | undefined;
    speedRating?: number | undefined;
    speedTestResult?: string | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    signalRating?: number | undefined;
    valueRating?: number | undefined;
    serviceRating?: number | undefined;
    usageDuration?: number | undefined;
    actualDataUsed?: string | undefined;
    deviceUsed?: string | undefined;
    activationExperience?: string | undefined;
    signalQuality?: "excellent" | "good" | "average" | "poor" | "very_poor" | undefined;
    purchaseVerified?: boolean | undefined;
    reviewDate?: number | undefined;
    status: "approved" | "rejected" | "pending";
    content: string;
    createdAt: number;
    wouldRecommend: boolean;
    reportCount: number;
    overallRating: number;
    isVerified: boolean;
    helpfulCount: number;
    simCardId: import("convex/values").GenericId<"simCards">;
}>>;
export declare const getTopReviews: import("convex/server").RegisteredQuery<"public", {
    limit?: number | undefined;
    simCardId?: import("convex/values").GenericId<"simCards"> | undefined;
}, Promise<{
    _id: import("convex/values").GenericId<"simCardReviews">;
    _creationTime: number;
    title?: string | undefined;
    destination?: string | undefined;
    userId?: string | undefined;
    updatedAt?: number | undefined;
    imageUrls?: string[] | undefined;
    authorName?: string | undefined;
    speedRating?: number | undefined;
    speedTestResult?: string | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    signalRating?: number | undefined;
    valueRating?: number | undefined;
    serviceRating?: number | undefined;
    usageDuration?: number | undefined;
    actualDataUsed?: string | undefined;
    deviceUsed?: string | undefined;
    activationExperience?: string | undefined;
    signalQuality?: "excellent" | "good" | "average" | "poor" | "very_poor" | undefined;
    purchaseVerified?: boolean | undefined;
    reviewDate?: number | undefined;
    status: "approved" | "rejected" | "pending";
    content: string;
    createdAt: number;
    wouldRecommend: boolean;
    reportCount: number;
    overallRating: number;
    isVerified: boolean;
    helpfulCount: number;
    simCardId: import("convex/values").GenericId<"simCards">;
}[]>>;
export declare const create: import("convex/server").RegisteredMutation<"public", {
    title?: string | undefined;
    destination?: string | undefined;
    userId?: string | undefined;
    imageUrls?: string[] | undefined;
    authorName?: string | undefined;
    speedRating?: number | undefined;
    speedTestResult?: string | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    signalRating?: number | undefined;
    valueRating?: number | undefined;
    serviceRating?: number | undefined;
    usageDuration?: number | undefined;
    actualDataUsed?: string | undefined;
    deviceUsed?: string | undefined;
    activationExperience?: string | undefined;
    signalQuality?: "excellent" | "good" | "average" | "poor" | "very_poor" | undefined;
    content: string;
    wouldRecommend: boolean;
    overallRating: number;
    simCardId: import("convex/values").GenericId<"simCards">;
}, Promise<import("convex/values").GenericId<"simCardReviews">>>;
export declare const update: import("convex/server").RegisteredMutation<"public", {
    title?: string | undefined;
    destination?: string | undefined;
    content?: string | undefined;
    imageUrls?: string[] | undefined;
    wouldRecommend?: boolean | undefined;
    overallRating?: number | undefined;
    speedRating?: number | undefined;
    speedTestResult?: string | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    signalRating?: number | undefined;
    valueRating?: number | undefined;
    serviceRating?: number | undefined;
    usageDuration?: number | undefined;
    actualDataUsed?: string | undefined;
    deviceUsed?: string | undefined;
    activationExperience?: string | undefined;
    signalQuality?: "excellent" | "good" | "average" | "poor" | "very_poor" | undefined;
    id: import("convex/values").GenericId<"simCardReviews">;
}, Promise<{
    _id: import("convex/values").GenericId<"simCardReviews">;
    _creationTime: number;
    title?: string | undefined;
    destination?: string | undefined;
    userId?: string | undefined;
    updatedAt?: number | undefined;
    imageUrls?: string[] | undefined;
    authorName?: string | undefined;
    speedRating?: number | undefined;
    speedTestResult?: string | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    signalRating?: number | undefined;
    valueRating?: number | undefined;
    serviceRating?: number | undefined;
    usageDuration?: number | undefined;
    actualDataUsed?: string | undefined;
    deviceUsed?: string | undefined;
    activationExperience?: string | undefined;
    signalQuality?: "excellent" | "good" | "average" | "poor" | "very_poor" | undefined;
    purchaseVerified?: boolean | undefined;
    reviewDate?: number | undefined;
    status: "approved" | "rejected" | "pending";
    content: string;
    createdAt: number;
    wouldRecommend: boolean;
    reportCount: number;
    overallRating: number;
    isVerified: boolean;
    helpfulCount: number;
    simCardId: import("convex/values").GenericId<"simCards">;
} | null>>;
export declare const updateStatus: import("convex/server").RegisteredMutation<"public", {
    status: "approved" | "rejected" | "pending";
    id: import("convex/values").GenericId<"simCardReviews">;
}, Promise<{
    _id: import("convex/values").GenericId<"simCardReviews">;
    _creationTime: number;
    title?: string | undefined;
    destination?: string | undefined;
    userId?: string | undefined;
    updatedAt?: number | undefined;
    imageUrls?: string[] | undefined;
    authorName?: string | undefined;
    speedRating?: number | undefined;
    speedTestResult?: string | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    signalRating?: number | undefined;
    valueRating?: number | undefined;
    serviceRating?: number | undefined;
    usageDuration?: number | undefined;
    actualDataUsed?: string | undefined;
    deviceUsed?: string | undefined;
    activationExperience?: string | undefined;
    signalQuality?: "excellent" | "good" | "average" | "poor" | "very_poor" | undefined;
    purchaseVerified?: boolean | undefined;
    reviewDate?: number | undefined;
    status: "approved" | "rejected" | "pending";
    content: string;
    createdAt: number;
    wouldRecommend: boolean;
    reportCount: number;
    overallRating: number;
    isVerified: boolean;
    helpfulCount: number;
    simCardId: import("convex/values").GenericId<"simCards">;
} | null>>;
export declare const vote: import("convex/server").RegisteredMutation<"public", {
    userId: string;
    voteType: "helpful" | "not_helpful";
    reviewId: import("convex/values").GenericId<"simCardReviews">;
}, Promise<{
    _id: import("convex/values").GenericId<"simCardReviews">;
    _creationTime: number;
    title?: string | undefined;
    destination?: string | undefined;
    userId?: string | undefined;
    updatedAt?: number | undefined;
    imageUrls?: string[] | undefined;
    authorName?: string | undefined;
    speedRating?: number | undefined;
    speedTestResult?: string | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    signalRating?: number | undefined;
    valueRating?: number | undefined;
    serviceRating?: number | undefined;
    usageDuration?: number | undefined;
    actualDataUsed?: string | undefined;
    deviceUsed?: string | undefined;
    activationExperience?: string | undefined;
    signalQuality?: "excellent" | "good" | "average" | "poor" | "very_poor" | undefined;
    purchaseVerified?: boolean | undefined;
    reviewDate?: number | undefined;
    status: "approved" | "rejected" | "pending";
    content: string;
    createdAt: number;
    wouldRecommend: boolean;
    reportCount: number;
    overallRating: number;
    isVerified: boolean;
    helpfulCount: number;
    simCardId: import("convex/values").GenericId<"simCards">;
} | null>>;
export declare const getUserVote: import("convex/server").RegisteredQuery<"public", {
    userId: string;
    reviewId: import("convex/values").GenericId<"simCardReviews">;
}, Promise<{
    _id: import("convex/values").GenericId<"simCardReviewVotes">;
    _creationTime: number;
    userId: string;
    createdAt: number;
    voteType: "helpful" | "not_helpful";
    reviewId: import("convex/values").GenericId<"simCardReviews">;
}>>;
export declare const report: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"simCardReviews">;
}, Promise<{
    _id: import("convex/values").GenericId<"simCardReviews">;
    _creationTime: number;
    title?: string | undefined;
    destination?: string | undefined;
    userId?: string | undefined;
    updatedAt?: number | undefined;
    imageUrls?: string[] | undefined;
    authorName?: string | undefined;
    speedRating?: number | undefined;
    speedTestResult?: string | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    signalRating?: number | undefined;
    valueRating?: number | undefined;
    serviceRating?: number | undefined;
    usageDuration?: number | undefined;
    actualDataUsed?: string | undefined;
    deviceUsed?: string | undefined;
    activationExperience?: string | undefined;
    signalQuality?: "excellent" | "good" | "average" | "poor" | "very_poor" | undefined;
    purchaseVerified?: boolean | undefined;
    reviewDate?: number | undefined;
    status: "approved" | "rejected" | "pending";
    content: string;
    createdAt: number;
    wouldRecommend: boolean;
    reportCount: number;
    overallRating: number;
    isVerified: boolean;
    helpfulCount: number;
    simCardId: import("convex/values").GenericId<"simCards">;
} | null>>;
export declare const remove: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"simCardReviews">;
}, Promise<void>>;
