export declare const list: import("convex/server").RegisteredQuery<"public", {
    destination?: string | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
    minDays?: number | undefined;
    coverageType?: "single_country" | "regional" | "global" | undefined;
    cardType?: "physical" | "esim" | "wifi_device" | undefined;
    includesVoice?: boolean | undefined;
    maxPrice?: number | undefined;
    minData?: number | undefined;
}, Promise<{
    _id: import("convex/values").GenericId<"simCards">;
    _creationTime: number;
    nameEn?: string | undefined;
    rating?: number | undefined;
    providerLogo?: string | undefined;
    destinationNames?: string[] | undefined;
    regionName?: string | undefined;
    supportedCarriers?: string[] | undefined;
    esimInfo?: {
        activationInstructions?: string | undefined;
        compatibleDevices?: string[] | undefined;
        supportsQrActivation: boolean;
        supportsAppActivation: boolean;
        requiresUnlockedPhone: boolean;
    } | undefined;
    physicalSimInfo?: {
        deliveryOptions?: {
            description?: string | undefined;
            estimatedDays?: number | undefined;
            fee?: number | undefined;
            method: string;
        }[] | undefined;
        pickupLocations?: string[] | undefined;
        simSize: string[];
    } | undefined;
    voiceMinutes?: number | undefined;
    smsCount?: number | undefined;
    localNumber?: boolean | undefined;
    maxDevices?: number | undefined;
    purchasePlatforms?: string[] | undefined;
    affiliateUrl?: string | undefined;
    salesCount?: number | undefined;
    isPromoted?: boolean | undefined;
    createdAt: number;
    name: string;
    priority: number;
    destinations: string[];
    provider: string;
    updatedAt: number;
    purchaseUrl: string;
    isActive: boolean;
    features: string[];
    reviewCount: number;
    coverageType: "single_country" | "regional" | "global";
    cardType: "physical" | "esim" | "wifi_device";
    dataPlans: {
        originalPrice?: number | undefined;
        pricePerDay?: number | undefined;
        dataAmountBytes?: number | undefined;
        throttledSpeedAfterLimit?: string | undefined;
        pricePerGB?: number | undefined;
        currency: string;
        price: number;
        dataAmount: string;
        isUnlimited: boolean;
        validityDays: number;
    }[];
    networkType: string[];
    includesVoice: boolean;
    includesSms: boolean;
    hotspotSupported: boolean;
}[]>>;
export declare const getById: import("convex/server").RegisteredQuery<"public", {
    id: import("convex/values").GenericId<"simCards">;
}, Promise<{
    _id: import("convex/values").GenericId<"simCards">;
    _creationTime: number;
    nameEn?: string | undefined;
    rating?: number | undefined;
    providerLogo?: string | undefined;
    destinationNames?: string[] | undefined;
    regionName?: string | undefined;
    supportedCarriers?: string[] | undefined;
    esimInfo?: {
        activationInstructions?: string | undefined;
        compatibleDevices?: string[] | undefined;
        supportsQrActivation: boolean;
        supportsAppActivation: boolean;
        requiresUnlockedPhone: boolean;
    } | undefined;
    physicalSimInfo?: {
        deliveryOptions?: {
            description?: string | undefined;
            estimatedDays?: number | undefined;
            fee?: number | undefined;
            method: string;
        }[] | undefined;
        pickupLocations?: string[] | undefined;
        simSize: string[];
    } | undefined;
    voiceMinutes?: number | undefined;
    smsCount?: number | undefined;
    localNumber?: boolean | undefined;
    maxDevices?: number | undefined;
    purchasePlatforms?: string[] | undefined;
    affiliateUrl?: string | undefined;
    salesCount?: number | undefined;
    isPromoted?: boolean | undefined;
    createdAt: number;
    name: string;
    priority: number;
    destinations: string[];
    provider: string;
    updatedAt: number;
    purchaseUrl: string;
    isActive: boolean;
    features: string[];
    reviewCount: number;
    coverageType: "single_country" | "regional" | "global";
    cardType: "physical" | "esim" | "wifi_device";
    dataPlans: {
        originalPrice?: number | undefined;
        pricePerDay?: number | undefined;
        dataAmountBytes?: number | undefined;
        throttledSpeedAfterLimit?: string | undefined;
        pricePerGB?: number | undefined;
        currency: string;
        price: number;
        dataAmount: string;
        isUnlimited: boolean;
        validityDays: number;
    }[];
    networkType: string[];
    includesVoice: boolean;
    includesSms: boolean;
    hotspotSupported: boolean;
} | null>>;
export declare const getRecommended: import("convex/server").RegisteredQuery<"public", {
    limit?: number | undefined;
    tripDurationDays?: number | undefined;
    needsVoice?: boolean | undefined;
    preferEsim?: boolean | undefined;
    destination: string;
}, Promise<{
    _id: import("convex/values").GenericId<"simCards">;
    _creationTime: number;
    nameEn?: string | undefined;
    rating?: number | undefined;
    providerLogo?: string | undefined;
    destinationNames?: string[] | undefined;
    regionName?: string | undefined;
    supportedCarriers?: string[] | undefined;
    esimInfo?: {
        activationInstructions?: string | undefined;
        compatibleDevices?: string[] | undefined;
        supportsQrActivation: boolean;
        supportsAppActivation: boolean;
        requiresUnlockedPhone: boolean;
    } | undefined;
    physicalSimInfo?: {
        deliveryOptions?: {
            description?: string | undefined;
            estimatedDays?: number | undefined;
            fee?: number | undefined;
            method: string;
        }[] | undefined;
        pickupLocations?: string[] | undefined;
        simSize: string[];
    } | undefined;
    voiceMinutes?: number | undefined;
    smsCount?: number | undefined;
    localNumber?: boolean | undefined;
    maxDevices?: number | undefined;
    purchasePlatforms?: string[] | undefined;
    affiliateUrl?: string | undefined;
    salesCount?: number | undefined;
    isPromoted?: boolean | undefined;
    createdAt: number;
    name: string;
    priority: number;
    destinations: string[];
    provider: string;
    updatedAt: number;
    purchaseUrl: string;
    isActive: boolean;
    features: string[];
    reviewCount: number;
    coverageType: "single_country" | "regional" | "global";
    cardType: "physical" | "esim" | "wifi_device";
    dataPlans: {
        originalPrice?: number | undefined;
        pricePerDay?: number | undefined;
        dataAmountBytes?: number | undefined;
        throttledSpeedAfterLimit?: string | undefined;
        pricePerGB?: number | undefined;
        currency: string;
        price: number;
        dataAmount: string;
        isUnlimited: boolean;
        validityDays: number;
    }[];
    networkType: string[];
    includesVoice: boolean;
    includesSms: boolean;
    hotspotSupported: boolean;
}[]>>;
export declare const search: import("convex/server").RegisteredQuery<"public", {
    destination?: string | undefined;
    limit?: number | undefined;
    query: string;
}, Promise<{
    _id: import("convex/values").GenericId<"simCards">;
    _creationTime: number;
    nameEn?: string | undefined;
    rating?: number | undefined;
    providerLogo?: string | undefined;
    destinationNames?: string[] | undefined;
    regionName?: string | undefined;
    supportedCarriers?: string[] | undefined;
    esimInfo?: {
        activationInstructions?: string | undefined;
        compatibleDevices?: string[] | undefined;
        supportsQrActivation: boolean;
        supportsAppActivation: boolean;
        requiresUnlockedPhone: boolean;
    } | undefined;
    physicalSimInfo?: {
        deliveryOptions?: {
            description?: string | undefined;
            estimatedDays?: number | undefined;
            fee?: number | undefined;
            method: string;
        }[] | undefined;
        pickupLocations?: string[] | undefined;
        simSize: string[];
    } | undefined;
    voiceMinutes?: number | undefined;
    smsCount?: number | undefined;
    localNumber?: boolean | undefined;
    maxDevices?: number | undefined;
    purchasePlatforms?: string[] | undefined;
    affiliateUrl?: string | undefined;
    salesCount?: number | undefined;
    isPromoted?: boolean | undefined;
    createdAt: number;
    name: string;
    priority: number;
    destinations: string[];
    provider: string;
    updatedAt: number;
    purchaseUrl: string;
    isActive: boolean;
    features: string[];
    reviewCount: number;
    coverageType: "single_country" | "regional" | "global";
    cardType: "physical" | "esim" | "wifi_device";
    dataPlans: {
        originalPrice?: number | undefined;
        pricePerDay?: number | undefined;
        dataAmountBytes?: number | undefined;
        throttledSpeedAfterLimit?: string | undefined;
        pricePerGB?: number | undefined;
        currency: string;
        price: number;
        dataAmount: string;
        isUnlimited: boolean;
        validityDays: number;
    }[];
    networkType: string[];
    includesVoice: boolean;
    includesSms: boolean;
    hotspotSupported: boolean;
}[]>>;
export declare const compare: import("convex/server").RegisteredQuery<"public", {
    ids: import("convex/values").GenericId<"simCards">[];
}, Promise<{
    _id: import("convex/values").GenericId<"simCards">;
    _creationTime: number;
    nameEn?: string | undefined;
    rating?: number | undefined;
    providerLogo?: string | undefined;
    destinationNames?: string[] | undefined;
    regionName?: string | undefined;
    supportedCarriers?: string[] | undefined;
    esimInfo?: {
        activationInstructions?: string | undefined;
        compatibleDevices?: string[] | undefined;
        supportsQrActivation: boolean;
        supportsAppActivation: boolean;
        requiresUnlockedPhone: boolean;
    } | undefined;
    physicalSimInfo?: {
        deliveryOptions?: {
            description?: string | undefined;
            estimatedDays?: number | undefined;
            fee?: number | undefined;
            method: string;
        }[] | undefined;
        pickupLocations?: string[] | undefined;
        simSize: string[];
    } | undefined;
    voiceMinutes?: number | undefined;
    smsCount?: number | undefined;
    localNumber?: boolean | undefined;
    maxDevices?: number | undefined;
    purchasePlatforms?: string[] | undefined;
    affiliateUrl?: string | undefined;
    salesCount?: number | undefined;
    isPromoted?: boolean | undefined;
    createdAt: number;
    name: string;
    priority: number;
    destinations: string[];
    provider: string;
    updatedAt: number;
    purchaseUrl: string;
    isActive: boolean;
    features: string[];
    reviewCount: number;
    coverageType: "single_country" | "regional" | "global";
    cardType: "physical" | "esim" | "wifi_device";
    dataPlans: {
        originalPrice?: number | undefined;
        pricePerDay?: number | undefined;
        dataAmountBytes?: number | undefined;
        throttledSpeedAfterLimit?: string | undefined;
        pricePerGB?: number | undefined;
        currency: string;
        price: number;
        dataAmount: string;
        isUnlimited: boolean;
        validityDays: number;
    }[];
    networkType: string[];
    includesVoice: boolean;
    includesSms: boolean;
    hotspotSupported: boolean;
}[]>>;
export declare const getPopular: import("convex/server").RegisteredQuery<"public", {
    destination?: string | undefined;
    limit?: number | undefined;
}, Promise<{
    _id: import("convex/values").GenericId<"simCards">;
    _creationTime: number;
    nameEn?: string | undefined;
    rating?: number | undefined;
    providerLogo?: string | undefined;
    destinationNames?: string[] | undefined;
    regionName?: string | undefined;
    supportedCarriers?: string[] | undefined;
    esimInfo?: {
        activationInstructions?: string | undefined;
        compatibleDevices?: string[] | undefined;
        supportsQrActivation: boolean;
        supportsAppActivation: boolean;
        requiresUnlockedPhone: boolean;
    } | undefined;
    physicalSimInfo?: {
        deliveryOptions?: {
            description?: string | undefined;
            estimatedDays?: number | undefined;
            fee?: number | undefined;
            method: string;
        }[] | undefined;
        pickupLocations?: string[] | undefined;
        simSize: string[];
    } | undefined;
    voiceMinutes?: number | undefined;
    smsCount?: number | undefined;
    localNumber?: boolean | undefined;
    maxDevices?: number | undefined;
    purchasePlatforms?: string[] | undefined;
    affiliateUrl?: string | undefined;
    salesCount?: number | undefined;
    isPromoted?: boolean | undefined;
    createdAt: number;
    name: string;
    priority: number;
    destinations: string[];
    provider: string;
    updatedAt: number;
    purchaseUrl: string;
    isActive: boolean;
    features: string[];
    reviewCount: number;
    coverageType: "single_country" | "regional" | "global";
    cardType: "physical" | "esim" | "wifi_device";
    dataPlans: {
        originalPrice?: number | undefined;
        pricePerDay?: number | undefined;
        dataAmountBytes?: number | undefined;
        throttledSpeedAfterLimit?: string | undefined;
        pricePerGB?: number | undefined;
        currency: string;
        price: number;
        dataAmount: string;
        isUnlimited: boolean;
        validityDays: number;
    }[];
    networkType: string[];
    includesVoice: boolean;
    includesSms: boolean;
    hotspotSupported: boolean;
}[]>>;
export declare const getByRegion: import("convex/server").RegisteredQuery<"public", {
    limit?: number | undefined;
    region: string;
}, Promise<{
    _id: import("convex/values").GenericId<"simCards">;
    _creationTime: number;
    nameEn?: string | undefined;
    rating?: number | undefined;
    providerLogo?: string | undefined;
    destinationNames?: string[] | undefined;
    regionName?: string | undefined;
    supportedCarriers?: string[] | undefined;
    esimInfo?: {
        activationInstructions?: string | undefined;
        compatibleDevices?: string[] | undefined;
        supportsQrActivation: boolean;
        supportsAppActivation: boolean;
        requiresUnlockedPhone: boolean;
    } | undefined;
    physicalSimInfo?: {
        deliveryOptions?: {
            description?: string | undefined;
            estimatedDays?: number | undefined;
            fee?: number | undefined;
            method: string;
        }[] | undefined;
        pickupLocations?: string[] | undefined;
        simSize: string[];
    } | undefined;
    voiceMinutes?: number | undefined;
    smsCount?: number | undefined;
    localNumber?: boolean | undefined;
    maxDevices?: number | undefined;
    purchasePlatforms?: string[] | undefined;
    affiliateUrl?: string | undefined;
    salesCount?: number | undefined;
    isPromoted?: boolean | undefined;
    createdAt: number;
    name: string;
    priority: number;
    destinations: string[];
    provider: string;
    updatedAt: number;
    purchaseUrl: string;
    isActive: boolean;
    features: string[];
    reviewCount: number;
    coverageType: "single_country" | "regional" | "global";
    cardType: "physical" | "esim" | "wifi_device";
    dataPlans: {
        originalPrice?: number | undefined;
        pricePerDay?: number | undefined;
        dataAmountBytes?: number | undefined;
        throttledSpeedAfterLimit?: string | undefined;
        pricePerGB?: number | undefined;
        currency: string;
        price: number;
        dataAmount: string;
        isUnlimited: boolean;
        validityDays: number;
    }[];
    networkType: string[];
    includesVoice: boolean;
    includesSms: boolean;
    hotspotSupported: boolean;
}[]>>;
export declare const getEsimProducts: import("convex/server").RegisteredQuery<"public", {
    destination?: string | undefined;
    limit?: number | undefined;
}, Promise<{
    _id: import("convex/values").GenericId<"simCards">;
    _creationTime: number;
    nameEn?: string | undefined;
    rating?: number | undefined;
    providerLogo?: string | undefined;
    destinationNames?: string[] | undefined;
    regionName?: string | undefined;
    supportedCarriers?: string[] | undefined;
    esimInfo?: {
        activationInstructions?: string | undefined;
        compatibleDevices?: string[] | undefined;
        supportsQrActivation: boolean;
        supportsAppActivation: boolean;
        requiresUnlockedPhone: boolean;
    } | undefined;
    physicalSimInfo?: {
        deliveryOptions?: {
            description?: string | undefined;
            estimatedDays?: number | undefined;
            fee?: number | undefined;
            method: string;
        }[] | undefined;
        pickupLocations?: string[] | undefined;
        simSize: string[];
    } | undefined;
    voiceMinutes?: number | undefined;
    smsCount?: number | undefined;
    localNumber?: boolean | undefined;
    maxDevices?: number | undefined;
    purchasePlatforms?: string[] | undefined;
    affiliateUrl?: string | undefined;
    salesCount?: number | undefined;
    isPromoted?: boolean | undefined;
    createdAt: number;
    name: string;
    priority: number;
    destinations: string[];
    provider: string;
    updatedAt: number;
    purchaseUrl: string;
    isActive: boolean;
    features: string[];
    reviewCount: number;
    coverageType: "single_country" | "regional" | "global";
    cardType: "physical" | "esim" | "wifi_device";
    dataPlans: {
        originalPrice?: number | undefined;
        pricePerDay?: number | undefined;
        dataAmountBytes?: number | undefined;
        throttledSpeedAfterLimit?: string | undefined;
        pricePerGB?: number | undefined;
        currency: string;
        price: number;
        dataAmount: string;
        isUnlimited: boolean;
        validityDays: number;
    }[];
    networkType: string[];
    includesVoice: boolean;
    includesSms: boolean;
    hotspotSupported: boolean;
}[]>>;
export declare const create: import("convex/server").RegisteredMutation<"public", {
    priority?: number | undefined;
    nameEn?: string | undefined;
    providerLogo?: string | undefined;
    destinationNames?: string[] | undefined;
    regionName?: string | undefined;
    supportedCarriers?: string[] | undefined;
    esimInfo?: {
        activationInstructions?: string | undefined;
        compatibleDevices?: string[] | undefined;
        supportsQrActivation: boolean;
        supportsAppActivation: boolean;
        requiresUnlockedPhone: boolean;
    } | undefined;
    physicalSimInfo?: {
        deliveryOptions?: {
            description?: string | undefined;
            estimatedDays?: number | undefined;
            fee?: number | undefined;
            method: string;
        }[] | undefined;
        pickupLocations?: string[] | undefined;
        simSize: string[];
    } | undefined;
    voiceMinutes?: number | undefined;
    smsCount?: number | undefined;
    localNumber?: boolean | undefined;
    maxDevices?: number | undefined;
    purchasePlatforms?: string[] | undefined;
    affiliateUrl?: string | undefined;
    isPromoted?: boolean | undefined;
    name: string;
    destinations: string[];
    provider: string;
    purchaseUrl: string;
    features: string[];
    coverageType: "single_country" | "regional" | "global";
    cardType: "physical" | "esim" | "wifi_device";
    dataPlans: {
        originalPrice?: number | undefined;
        pricePerDay?: number | undefined;
        dataAmountBytes?: number | undefined;
        throttledSpeedAfterLimit?: string | undefined;
        pricePerGB?: number | undefined;
        currency: string;
        price: number;
        dataAmount: string;
        isUnlimited: boolean;
        validityDays: number;
    }[];
    networkType: string[];
    includesVoice: boolean;
    includesSms: boolean;
    hotspotSupported: boolean;
}, Promise<import("convex/values").GenericId<"simCards">>>;
export declare const update: import("convex/server").RegisteredMutation<"public", {
    name?: string | undefined;
    priority?: number | undefined;
    destinations?: string[] | undefined;
    provider?: string | undefined;
    nameEn?: string | undefined;
    purchaseUrl?: string | undefined;
    isActive?: boolean | undefined;
    providerLogo?: string | undefined;
    features?: string[] | undefined;
    coverageType?: "single_country" | "regional" | "global" | undefined;
    cardType?: "physical" | "esim" | "wifi_device" | undefined;
    destinationNames?: string[] | undefined;
    regionName?: string | undefined;
    dataPlans?: {
        originalPrice?: number | undefined;
        pricePerDay?: number | undefined;
        dataAmountBytes?: number | undefined;
        throttledSpeedAfterLimit?: string | undefined;
        pricePerGB?: number | undefined;
        currency: string;
        price: number;
        dataAmount: string;
        isUnlimited: boolean;
        validityDays: number;
    }[] | undefined;
    networkType?: string[] | undefined;
    supportedCarriers?: string[] | undefined;
    esimInfo?: {
        activationInstructions?: string | undefined;
        compatibleDevices?: string[] | undefined;
        supportsQrActivation: boolean;
        supportsAppActivation: boolean;
        requiresUnlockedPhone: boolean;
    } | undefined;
    physicalSimInfo?: {
        deliveryOptions?: {
            description?: string | undefined;
            estimatedDays?: number | undefined;
            fee?: number | undefined;
            method: string;
        }[] | undefined;
        pickupLocations?: string[] | undefined;
        simSize: string[];
    } | undefined;
    includesVoice?: boolean | undefined;
    voiceMinutes?: number | undefined;
    includesSms?: boolean | undefined;
    smsCount?: number | undefined;
    localNumber?: boolean | undefined;
    hotspotSupported?: boolean | undefined;
    maxDevices?: number | undefined;
    purchasePlatforms?: string[] | undefined;
    affiliateUrl?: string | undefined;
    isPromoted?: boolean | undefined;
    id: import("convex/values").GenericId<"simCards">;
}, Promise<{
    _id: import("convex/values").GenericId<"simCards">;
    _creationTime: number;
    nameEn?: string | undefined;
    rating?: number | undefined;
    providerLogo?: string | undefined;
    destinationNames?: string[] | undefined;
    regionName?: string | undefined;
    supportedCarriers?: string[] | undefined;
    esimInfo?: {
        activationInstructions?: string | undefined;
        compatibleDevices?: string[] | undefined;
        supportsQrActivation: boolean;
        supportsAppActivation: boolean;
        requiresUnlockedPhone: boolean;
    } | undefined;
    physicalSimInfo?: {
        deliveryOptions?: {
            description?: string | undefined;
            estimatedDays?: number | undefined;
            fee?: number | undefined;
            method: string;
        }[] | undefined;
        pickupLocations?: string[] | undefined;
        simSize: string[];
    } | undefined;
    voiceMinutes?: number | undefined;
    smsCount?: number | undefined;
    localNumber?: boolean | undefined;
    maxDevices?: number | undefined;
    purchasePlatforms?: string[] | undefined;
    affiliateUrl?: string | undefined;
    salesCount?: number | undefined;
    isPromoted?: boolean | undefined;
    createdAt: number;
    name: string;
    priority: number;
    destinations: string[];
    provider: string;
    updatedAt: number;
    purchaseUrl: string;
    isActive: boolean;
    features: string[];
    reviewCount: number;
    coverageType: "single_country" | "regional" | "global";
    cardType: "physical" | "esim" | "wifi_device";
    dataPlans: {
        originalPrice?: number | undefined;
        pricePerDay?: number | undefined;
        dataAmountBytes?: number | undefined;
        throttledSpeedAfterLimit?: string | undefined;
        pricePerGB?: number | undefined;
        currency: string;
        price: number;
        dataAmount: string;
        isUnlimited: boolean;
        validityDays: number;
    }[];
    networkType: string[];
    includesVoice: boolean;
    includesSms: boolean;
    hotspotSupported: boolean;
} | null>>;
export declare const remove: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"simCards">;
}, Promise<void>>;
export declare const updateRating: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"simCards">;
    rating: number;
    reviewCount: number;
}, Promise<{
    _id: import("convex/values").GenericId<"simCards">;
    _creationTime: number;
    nameEn?: string | undefined;
    rating?: number | undefined;
    providerLogo?: string | undefined;
    destinationNames?: string[] | undefined;
    regionName?: string | undefined;
    supportedCarriers?: string[] | undefined;
    esimInfo?: {
        activationInstructions?: string | undefined;
        compatibleDevices?: string[] | undefined;
        supportsQrActivation: boolean;
        supportsAppActivation: boolean;
        requiresUnlockedPhone: boolean;
    } | undefined;
    physicalSimInfo?: {
        deliveryOptions?: {
            description?: string | undefined;
            estimatedDays?: number | undefined;
            fee?: number | undefined;
            method: string;
        }[] | undefined;
        pickupLocations?: string[] | undefined;
        simSize: string[];
    } | undefined;
    voiceMinutes?: number | undefined;
    smsCount?: number | undefined;
    localNumber?: boolean | undefined;
    maxDevices?: number | undefined;
    purchasePlatforms?: string[] | undefined;
    affiliateUrl?: string | undefined;
    salesCount?: number | undefined;
    isPromoted?: boolean | undefined;
    createdAt: number;
    name: string;
    priority: number;
    destinations: string[];
    provider: string;
    updatedAt: number;
    purchaseUrl: string;
    isActive: boolean;
    features: string[];
    reviewCount: number;
    coverageType: "single_country" | "regional" | "global";
    cardType: "physical" | "esim" | "wifi_device";
    dataPlans: {
        originalPrice?: number | undefined;
        pricePerDay?: number | undefined;
        dataAmountBytes?: number | undefined;
        throttledSpeedAfterLimit?: string | undefined;
        pricePerGB?: number | undefined;
        currency: string;
        price: number;
        dataAmount: string;
        isUnlimited: boolean;
        validityDays: number;
    }[];
    networkType: string[];
    includesVoice: boolean;
    includesSms: boolean;
    hotspotSupported: boolean;
} | null>>;
