/**
 * Travel Insurance - User's travel insurance information management
 */
export declare const listByUser: import("convex/server").RegisteredQuery<"public", {
    userId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"travelInsurance">;
    _creationTime: number;
    email?: string | undefined;
    notes?: string | undefined;
    coverageAmount?: string | undefined;
    exclusions?: string | undefined;
    website?: string | undefined;
    claimsPhone?: string | undefined;
    medicalCoverage?: string | undefined;
    evacuationCoverage?: string | undefined;
    policyDocumentUrl?: string | undefined;
    insuranceCardUrl?: string | undefined;
    coveredRegions?: string[] | undefined;
    userId: string;
    startDate: string;
    endDate: string;
    createdAt: number;
    updatedAt: number;
    isActive: boolean;
    policyNumber: string;
    providerName: string;
    emergencyHotline: string;
    coverageType: string;
}[]>>;
export declare const getById: import("convex/server").RegisteredQuery<"public", {
    id: import("convex/values").GenericId<"travelInsurance">;
}, Promise<{
    _id: import("convex/values").GenericId<"travelInsurance">;
    _creationTime: number;
    email?: string | undefined;
    notes?: string | undefined;
    coverageAmount?: string | undefined;
    exclusions?: string | undefined;
    website?: string | undefined;
    claimsPhone?: string | undefined;
    medicalCoverage?: string | undefined;
    evacuationCoverage?: string | undefined;
    policyDocumentUrl?: string | undefined;
    insuranceCardUrl?: string | undefined;
    coveredRegions?: string[] | undefined;
    userId: string;
    startDate: string;
    endDate: string;
    createdAt: number;
    updatedAt: number;
    isActive: boolean;
    policyNumber: string;
    providerName: string;
    emergencyHotline: string;
    coverageType: string;
} | null>>;
export declare const getActive: import("convex/server").RegisteredQuery<"public", {
    userId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"travelInsurance">;
    _creationTime: number;
    email?: string | undefined;
    notes?: string | undefined;
    coverageAmount?: string | undefined;
    exclusions?: string | undefined;
    website?: string | undefined;
    claimsPhone?: string | undefined;
    medicalCoverage?: string | undefined;
    evacuationCoverage?: string | undefined;
    policyDocumentUrl?: string | undefined;
    insuranceCardUrl?: string | undefined;
    coveredRegions?: string[] | undefined;
    userId: string;
    startDate: string;
    endDate: string;
    createdAt: number;
    updatedAt: number;
    isActive: boolean;
    policyNumber: string;
    providerName: string;
    emergencyHotline: string;
    coverageType: string;
}[]>>;
export declare const getCurrentValid: import("convex/server").RegisteredQuery<"public", {
    userId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"travelInsurance">;
    _creationTime: number;
    email?: string | undefined;
    notes?: string | undefined;
    coverageAmount?: string | undefined;
    exclusions?: string | undefined;
    website?: string | undefined;
    claimsPhone?: string | undefined;
    medicalCoverage?: string | undefined;
    evacuationCoverage?: string | undefined;
    policyDocumentUrl?: string | undefined;
    insuranceCardUrl?: string | undefined;
    coveredRegions?: string[] | undefined;
    userId: string;
    startDate: string;
    endDate: string;
    createdAt: number;
    updatedAt: number;
    isActive: boolean;
    policyNumber: string;
    providerName: string;
    emergencyHotline: string;
    coverageType: string;
}[]>>;
export declare const create: import("convex/server").RegisteredMutation<"public", {
    email?: string | undefined;
    notes?: string | undefined;
    coverageAmount?: string | undefined;
    exclusions?: string | undefined;
    website?: string | undefined;
    claimsPhone?: string | undefined;
    medicalCoverage?: string | undefined;
    evacuationCoverage?: string | undefined;
    policyDocumentUrl?: string | undefined;
    insuranceCardUrl?: string | undefined;
    coveredRegions?: string[] | undefined;
    userId: string;
    startDate: string;
    endDate: string;
    isActive: boolean;
    policyNumber: string;
    providerName: string;
    emergencyHotline: string;
    coverageType: string;
}, Promise<import("convex/values").GenericId<"travelInsurance">>>;
export declare const update: import("convex/server").RegisteredMutation<"public", {
    email?: string | undefined;
    startDate?: string | undefined;
    endDate?: string | undefined;
    notes?: string | undefined;
    isActive?: boolean | undefined;
    coverageAmount?: string | undefined;
    exclusions?: string | undefined;
    policyNumber?: string | undefined;
    website?: string | undefined;
    providerName?: string | undefined;
    emergencyHotline?: string | undefined;
    claimsPhone?: string | undefined;
    coverageType?: string | undefined;
    medicalCoverage?: string | undefined;
    evacuationCoverage?: string | undefined;
    policyDocumentUrl?: string | undefined;
    insuranceCardUrl?: string | undefined;
    coveredRegions?: string[] | undefined;
    id: import("convex/values").GenericId<"travelInsurance">;
}, Promise<{
    _id: import("convex/values").GenericId<"travelInsurance">;
    _creationTime: number;
    email?: string | undefined;
    notes?: string | undefined;
    coverageAmount?: string | undefined;
    exclusions?: string | undefined;
    website?: string | undefined;
    claimsPhone?: string | undefined;
    medicalCoverage?: string | undefined;
    evacuationCoverage?: string | undefined;
    policyDocumentUrl?: string | undefined;
    insuranceCardUrl?: string | undefined;
    coveredRegions?: string[] | undefined;
    userId: string;
    startDate: string;
    endDate: string;
    createdAt: number;
    updatedAt: number;
    isActive: boolean;
    policyNumber: string;
    providerName: string;
    emergencyHotline: string;
    coverageType: string;
} | null>>;
export declare const remove: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"travelInsurance">;
}, Promise<void>>;
export declare const toggleActive: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"travelInsurance">;
}, Promise<{
    _id: import("convex/values").GenericId<"travelInsurance">;
    _creationTime: number;
    email?: string | undefined;
    notes?: string | undefined;
    coverageAmount?: string | undefined;
    exclusions?: string | undefined;
    website?: string | undefined;
    claimsPhone?: string | undefined;
    medicalCoverage?: string | undefined;
    evacuationCoverage?: string | undefined;
    policyDocumentUrl?: string | undefined;
    insuranceCardUrl?: string | undefined;
    coveredRegions?: string[] | undefined;
    userId: string;
    startDate: string;
    endDate: string;
    createdAt: number;
    updatedAt: number;
    isActive: boolean;
    policyNumber: string;
    providerName: string;
    emergencyHotline: string;
    coverageType: string;
} | null>>;
