export declare const getVisaRequirement: import("convex/server").RegisteredQuery<"public", {
    originCountryCode: string;
    destinationCountryCode: string;
}, Promise<{
    _id: import("convex/values").GenericId<"visaRequirements">;
    _creationTime: number;
    sourceUrl?: string | undefined;
    verifiedBy?: string | undefined;
    serviceFee?: number | undefined;
    originCountryNameEn?: string | undefined;
    destinationCountryNameEn?: string | undefined;
    visaTypeNameEn?: string | undefined;
    maxStayDays?: number | undefined;
    validityPeriod?: string | undefined;
    entryType?: "single" | "multiple" | "dual" | undefined;
    processingTime?: string | undefined;
    processingTimeMin?: number | undefined;
    processingTimeMax?: number | undefined;
    expressFee?: number | undefined;
    expressProcessingTime?: string | undefined;
    visaFee?: number | undefined;
    visaFeeCurrency?: string | undefined;
    entryRequirements?: {
        travelInsurance?: boolean | undefined;
        passportValidity?: string | undefined;
        blankPages?: number | undefined;
        onwardTicket?: boolean | undefined;
        hotelBooking?: boolean | undefined;
        financialProof?: string | undefined;
        invitationLetter?: boolean | undefined;
        returnTicket?: boolean | undefined;
        additionalRequirements?: string[] | undefined;
    } | undefined;
    specialNotes?: string[] | undefined;
    warnings?: string[] | undefined;
    eVisaUrl?: string | undefined;
    eVisaProcessingDays?: number | undefined;
    voaPorts?: string[] | undefined;
    voaFee?: number | undefined;
    voaFeeCurrency?: string | undefined;
    createdAt: number;
    updatedAt: number;
    source: string;
    requiredDocuments: {
        description?: string | undefined;
        nameEn?: string | undefined;
        notes?: string | undefined;
        name: string;
        isRequired: boolean;
    }[];
    lastVerifiedAt: number;
    originCountryCode: string;
    originCountryName: string;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    visaTypeName: string;
    difficultyLevel: "moderate" | "very_easy" | "easy" | "difficult" | "very_difficult";
    applicationMethods: {
        email?: string | undefined;
        url?: string | undefined;
        phone?: string | undefined;
        nameEn?: string | undefined;
        address?: string | undefined;
        notes?: string | undefined;
        name: string;
        method: "online" | "embassy" | "consulate" | "visa_center" | "on_arrival";
    }[];
} | null>>;
export declare const listByOriginCountry: import("convex/server").RegisteredQuery<"public", {
    limit?: number | undefined;
    visaType?: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa" | undefined;
    originCountryCode: string;
}, Promise<{
    _id: import("convex/values").GenericId<"visaRequirements">;
    _creationTime: number;
    sourceUrl?: string | undefined;
    verifiedBy?: string | undefined;
    serviceFee?: number | undefined;
    originCountryNameEn?: string | undefined;
    destinationCountryNameEn?: string | undefined;
    visaTypeNameEn?: string | undefined;
    maxStayDays?: number | undefined;
    validityPeriod?: string | undefined;
    entryType?: "single" | "multiple" | "dual" | undefined;
    processingTime?: string | undefined;
    processingTimeMin?: number | undefined;
    processingTimeMax?: number | undefined;
    expressFee?: number | undefined;
    expressProcessingTime?: string | undefined;
    visaFee?: number | undefined;
    visaFeeCurrency?: string | undefined;
    entryRequirements?: {
        travelInsurance?: boolean | undefined;
        passportValidity?: string | undefined;
        blankPages?: number | undefined;
        onwardTicket?: boolean | undefined;
        hotelBooking?: boolean | undefined;
        financialProof?: string | undefined;
        invitationLetter?: boolean | undefined;
        returnTicket?: boolean | undefined;
        additionalRequirements?: string[] | undefined;
    } | undefined;
    specialNotes?: string[] | undefined;
    warnings?: string[] | undefined;
    eVisaUrl?: string | undefined;
    eVisaProcessingDays?: number | undefined;
    voaPorts?: string[] | undefined;
    voaFee?: number | undefined;
    voaFeeCurrency?: string | undefined;
    createdAt: number;
    updatedAt: number;
    source: string;
    requiredDocuments: {
        description?: string | undefined;
        nameEn?: string | undefined;
        notes?: string | undefined;
        name: string;
        isRequired: boolean;
    }[];
    lastVerifiedAt: number;
    originCountryCode: string;
    originCountryName: string;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    visaTypeName: string;
    difficultyLevel: "moderate" | "very_easy" | "easy" | "difficult" | "very_difficult";
    applicationMethods: {
        email?: string | undefined;
        url?: string | undefined;
        phone?: string | undefined;
        nameEn?: string | undefined;
        address?: string | undefined;
        notes?: string | undefined;
        name: string;
        method: "online" | "embassy" | "consulate" | "visa_center" | "on_arrival";
    }[];
}[]>>;
export declare const listVisaFreeDestinations: import("convex/server").RegisteredQuery<"public", {
    limit?: number | undefined;
    originCountryCode: string;
}, Promise<{
    _id: import("convex/values").GenericId<"visaRequirements">;
    _creationTime: number;
    sourceUrl?: string | undefined;
    verifiedBy?: string | undefined;
    serviceFee?: number | undefined;
    originCountryNameEn?: string | undefined;
    destinationCountryNameEn?: string | undefined;
    visaTypeNameEn?: string | undefined;
    maxStayDays?: number | undefined;
    validityPeriod?: string | undefined;
    entryType?: "single" | "multiple" | "dual" | undefined;
    processingTime?: string | undefined;
    processingTimeMin?: number | undefined;
    processingTimeMax?: number | undefined;
    expressFee?: number | undefined;
    expressProcessingTime?: string | undefined;
    visaFee?: number | undefined;
    visaFeeCurrency?: string | undefined;
    entryRequirements?: {
        travelInsurance?: boolean | undefined;
        passportValidity?: string | undefined;
        blankPages?: number | undefined;
        onwardTicket?: boolean | undefined;
        hotelBooking?: boolean | undefined;
        financialProof?: string | undefined;
        invitationLetter?: boolean | undefined;
        returnTicket?: boolean | undefined;
        additionalRequirements?: string[] | undefined;
    } | undefined;
    specialNotes?: string[] | undefined;
    warnings?: string[] | undefined;
    eVisaUrl?: string | undefined;
    eVisaProcessingDays?: number | undefined;
    voaPorts?: string[] | undefined;
    voaFee?: number | undefined;
    voaFeeCurrency?: string | undefined;
    createdAt: number;
    updatedAt: number;
    source: string;
    requiredDocuments: {
        description?: string | undefined;
        nameEn?: string | undefined;
        notes?: string | undefined;
        name: string;
        isRequired: boolean;
    }[];
    lastVerifiedAt: number;
    originCountryCode: string;
    originCountryName: string;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    visaTypeName: string;
    difficultyLevel: "moderate" | "very_easy" | "easy" | "difficult" | "very_difficult";
    applicationMethods: {
        email?: string | undefined;
        url?: string | undefined;
        phone?: string | undefined;
        nameEn?: string | undefined;
        address?: string | undefined;
        notes?: string | undefined;
        name: string;
        method: "online" | "embassy" | "consulate" | "visa_center" | "on_arrival";
    }[];
}[]>>;
export declare const listEVisaDestinations: import("convex/server").RegisteredQuery<"public", {
    limit?: number | undefined;
    originCountryCode: string;
}, Promise<{
    _id: import("convex/values").GenericId<"visaRequirements">;
    _creationTime: number;
    sourceUrl?: string | undefined;
    verifiedBy?: string | undefined;
    serviceFee?: number | undefined;
    originCountryNameEn?: string | undefined;
    destinationCountryNameEn?: string | undefined;
    visaTypeNameEn?: string | undefined;
    maxStayDays?: number | undefined;
    validityPeriod?: string | undefined;
    entryType?: "single" | "multiple" | "dual" | undefined;
    processingTime?: string | undefined;
    processingTimeMin?: number | undefined;
    processingTimeMax?: number | undefined;
    expressFee?: number | undefined;
    expressProcessingTime?: string | undefined;
    visaFee?: number | undefined;
    visaFeeCurrency?: string | undefined;
    entryRequirements?: {
        travelInsurance?: boolean | undefined;
        passportValidity?: string | undefined;
        blankPages?: number | undefined;
        onwardTicket?: boolean | undefined;
        hotelBooking?: boolean | undefined;
        financialProof?: string | undefined;
        invitationLetter?: boolean | undefined;
        returnTicket?: boolean | undefined;
        additionalRequirements?: string[] | undefined;
    } | undefined;
    specialNotes?: string[] | undefined;
    warnings?: string[] | undefined;
    eVisaUrl?: string | undefined;
    eVisaProcessingDays?: number | undefined;
    voaPorts?: string[] | undefined;
    voaFee?: number | undefined;
    voaFeeCurrency?: string | undefined;
    createdAt: number;
    updatedAt: number;
    source: string;
    requiredDocuments: {
        description?: string | undefined;
        nameEn?: string | undefined;
        notes?: string | undefined;
        name: string;
        isRequired: boolean;
    }[];
    lastVerifiedAt: number;
    originCountryCode: string;
    originCountryName: string;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    visaTypeName: string;
    difficultyLevel: "moderate" | "very_easy" | "easy" | "difficult" | "very_difficult";
    applicationMethods: {
        email?: string | undefined;
        url?: string | undefined;
        phone?: string | undefined;
        nameEn?: string | undefined;
        address?: string | undefined;
        notes?: string | undefined;
        name: string;
        method: "online" | "embassy" | "consulate" | "visa_center" | "on_arrival";
    }[];
}[]>>;
export declare const searchByDestination: import("convex/server").RegisteredQuery<"public", {
    limit?: number | undefined;
    query: string;
    originCountryCode: string;
}, Promise<{
    _id: import("convex/values").GenericId<"visaRequirements">;
    _creationTime: number;
    sourceUrl?: string | undefined;
    verifiedBy?: string | undefined;
    serviceFee?: number | undefined;
    originCountryNameEn?: string | undefined;
    destinationCountryNameEn?: string | undefined;
    visaTypeNameEn?: string | undefined;
    maxStayDays?: number | undefined;
    validityPeriod?: string | undefined;
    entryType?: "single" | "multiple" | "dual" | undefined;
    processingTime?: string | undefined;
    processingTimeMin?: number | undefined;
    processingTimeMax?: number | undefined;
    expressFee?: number | undefined;
    expressProcessingTime?: string | undefined;
    visaFee?: number | undefined;
    visaFeeCurrency?: string | undefined;
    entryRequirements?: {
        travelInsurance?: boolean | undefined;
        passportValidity?: string | undefined;
        blankPages?: number | undefined;
        onwardTicket?: boolean | undefined;
        hotelBooking?: boolean | undefined;
        financialProof?: string | undefined;
        invitationLetter?: boolean | undefined;
        returnTicket?: boolean | undefined;
        additionalRequirements?: string[] | undefined;
    } | undefined;
    specialNotes?: string[] | undefined;
    warnings?: string[] | undefined;
    eVisaUrl?: string | undefined;
    eVisaProcessingDays?: number | undefined;
    voaPorts?: string[] | undefined;
    voaFee?: number | undefined;
    voaFeeCurrency?: string | undefined;
    createdAt: number;
    updatedAt: number;
    source: string;
    requiredDocuments: {
        description?: string | undefined;
        nameEn?: string | undefined;
        notes?: string | undefined;
        name: string;
        isRequired: boolean;
    }[];
    lastVerifiedAt: number;
    originCountryCode: string;
    originCountryName: string;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    visaTypeName: string;
    difficultyLevel: "moderate" | "very_easy" | "easy" | "difficult" | "very_difficult";
    applicationMethods: {
        email?: string | undefined;
        url?: string | undefined;
        phone?: string | undefined;
        nameEn?: string | undefined;
        address?: string | undefined;
        notes?: string | undefined;
        name: string;
        method: "online" | "embassy" | "consulate" | "visa_center" | "on_arrival";
    }[];
}[]>>;
export declare const getById: import("convex/server").RegisteredQuery<"public", {
    id: import("convex/values").GenericId<"visaRequirements">;
}, Promise<{
    _id: import("convex/values").GenericId<"visaRequirements">;
    _creationTime: number;
    sourceUrl?: string | undefined;
    verifiedBy?: string | undefined;
    serviceFee?: number | undefined;
    originCountryNameEn?: string | undefined;
    destinationCountryNameEn?: string | undefined;
    visaTypeNameEn?: string | undefined;
    maxStayDays?: number | undefined;
    validityPeriod?: string | undefined;
    entryType?: "single" | "multiple" | "dual" | undefined;
    processingTime?: string | undefined;
    processingTimeMin?: number | undefined;
    processingTimeMax?: number | undefined;
    expressFee?: number | undefined;
    expressProcessingTime?: string | undefined;
    visaFee?: number | undefined;
    visaFeeCurrency?: string | undefined;
    entryRequirements?: {
        travelInsurance?: boolean | undefined;
        passportValidity?: string | undefined;
        blankPages?: number | undefined;
        onwardTicket?: boolean | undefined;
        hotelBooking?: boolean | undefined;
        financialProof?: string | undefined;
        invitationLetter?: boolean | undefined;
        returnTicket?: boolean | undefined;
        additionalRequirements?: string[] | undefined;
    } | undefined;
    specialNotes?: string[] | undefined;
    warnings?: string[] | undefined;
    eVisaUrl?: string | undefined;
    eVisaProcessingDays?: number | undefined;
    voaPorts?: string[] | undefined;
    voaFee?: number | undefined;
    voaFeeCurrency?: string | undefined;
    createdAt: number;
    updatedAt: number;
    source: string;
    requiredDocuments: {
        description?: string | undefined;
        nameEn?: string | undefined;
        notes?: string | undefined;
        name: string;
        isRequired: boolean;
    }[];
    lastVerifiedAt: number;
    originCountryCode: string;
    originCountryName: string;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    visaTypeName: string;
    difficultyLevel: "moderate" | "very_easy" | "easy" | "difficult" | "very_difficult";
    applicationMethods: {
        email?: string | undefined;
        url?: string | undefined;
        phone?: string | undefined;
        nameEn?: string | undefined;
        address?: string | undefined;
        notes?: string | undefined;
        name: string;
        method: "online" | "embassy" | "consulate" | "visa_center" | "on_arrival";
    }[];
} | null>>;
export declare const upsertVisaRequirement: import("convex/server").RegisteredMutation<"public", {
    sourceUrl?: string | undefined;
    verifiedBy?: string | undefined;
    serviceFee?: number | undefined;
    originCountryNameEn?: string | undefined;
    destinationCountryNameEn?: string | undefined;
    visaTypeNameEn?: string | undefined;
    maxStayDays?: number | undefined;
    validityPeriod?: string | undefined;
    entryType?: "single" | "multiple" | "dual" | undefined;
    processingTime?: string | undefined;
    processingTimeMin?: number | undefined;
    processingTimeMax?: number | undefined;
    expressFee?: number | undefined;
    expressProcessingTime?: string | undefined;
    visaFee?: number | undefined;
    visaFeeCurrency?: string | undefined;
    entryRequirements?: {
        travelInsurance?: boolean | undefined;
        passportValidity?: string | undefined;
        blankPages?: number | undefined;
        onwardTicket?: boolean | undefined;
        hotelBooking?: boolean | undefined;
        financialProof?: string | undefined;
        invitationLetter?: boolean | undefined;
        returnTicket?: boolean | undefined;
        additionalRequirements?: string[] | undefined;
    } | undefined;
    specialNotes?: string[] | undefined;
    warnings?: string[] | undefined;
    eVisaUrl?: string | undefined;
    eVisaProcessingDays?: number | undefined;
    voaPorts?: string[] | undefined;
    voaFee?: number | undefined;
    voaFeeCurrency?: string | undefined;
    source: string;
    requiredDocuments: {
        description?: string | undefined;
        nameEn?: string | undefined;
        notes?: string | undefined;
        name: string;
        isRequired: boolean;
    }[];
    originCountryCode: string;
    originCountryName: string;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    visaTypeName: string;
    difficultyLevel: "moderate" | "very_easy" | "easy" | "difficult" | "very_difficult";
    applicationMethods: {
        email?: string | undefined;
        url?: string | undefined;
        phone?: string | undefined;
        nameEn?: string | undefined;
        address?: string | undefined;
        notes?: string | undefined;
        name: string;
        method: "online" | "embassy" | "consulate" | "visa_center" | "on_arrival";
    }[];
}, Promise<import("convex/values").GenericId<"visaRequirements">>>;
export declare const updateVisaRequirement: import("convex/server").RegisteredMutation<"public", {
    verifiedBy?: string | undefined;
    requiredDocuments?: {
        description?: string | undefined;
        nameEn?: string | undefined;
        notes?: string | undefined;
        name: string;
        isRequired: boolean;
    }[] | undefined;
    visaType?: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa" | undefined;
    visaTypeName?: string | undefined;
    visaTypeNameEn?: string | undefined;
    difficultyLevel?: "moderate" | "very_easy" | "easy" | "difficult" | "very_difficult" | undefined;
    maxStayDays?: number | undefined;
    validityPeriod?: string | undefined;
    processingTime?: string | undefined;
    visaFee?: number | undefined;
    specialNotes?: string[] | undefined;
    warnings?: string[] | undefined;
    id: import("convex/values").GenericId<"visaRequirements">;
}, Promise<{
    _id: import("convex/values").GenericId<"visaRequirements">;
    _creationTime: number;
    sourceUrl?: string | undefined;
    verifiedBy?: string | undefined;
    serviceFee?: number | undefined;
    originCountryNameEn?: string | undefined;
    destinationCountryNameEn?: string | undefined;
    visaTypeNameEn?: string | undefined;
    maxStayDays?: number | undefined;
    validityPeriod?: string | undefined;
    entryType?: "single" | "multiple" | "dual" | undefined;
    processingTime?: string | undefined;
    processingTimeMin?: number | undefined;
    processingTimeMax?: number | undefined;
    expressFee?: number | undefined;
    expressProcessingTime?: string | undefined;
    visaFee?: number | undefined;
    visaFeeCurrency?: string | undefined;
    entryRequirements?: {
        travelInsurance?: boolean | undefined;
        passportValidity?: string | undefined;
        blankPages?: number | undefined;
        onwardTicket?: boolean | undefined;
        hotelBooking?: boolean | undefined;
        financialProof?: string | undefined;
        invitationLetter?: boolean | undefined;
        returnTicket?: boolean | undefined;
        additionalRequirements?: string[] | undefined;
    } | undefined;
    specialNotes?: string[] | undefined;
    warnings?: string[] | undefined;
    eVisaUrl?: string | undefined;
    eVisaProcessingDays?: number | undefined;
    voaPorts?: string[] | undefined;
    voaFee?: number | undefined;
    voaFeeCurrency?: string | undefined;
    createdAt: number;
    updatedAt: number;
    source: string;
    requiredDocuments: {
        description?: string | undefined;
        nameEn?: string | undefined;
        notes?: string | undefined;
        name: string;
        isRequired: boolean;
    }[];
    lastVerifiedAt: number;
    originCountryCode: string;
    originCountryName: string;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    visaTypeName: string;
    difficultyLevel: "moderate" | "very_easy" | "easy" | "difficult" | "very_difficult";
    applicationMethods: {
        email?: string | undefined;
        url?: string | undefined;
        phone?: string | undefined;
        nameEn?: string | undefined;
        address?: string | undefined;
        notes?: string | undefined;
        name: string;
        method: "online" | "embassy" | "consulate" | "visa_center" | "on_arrival";
    }[];
} | null>>;
export declare const getUserVisaReminders: import("convex/server").RegisteredQuery<"public", {
    status?: "completed" | "pending" | "dismissed" | "sent" | undefined;
    limit?: number | undefined;
    userId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"userVisaReminders">;
    _creationTime: number;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    sentAt?: number | undefined;
    visaRequirementId?: import("convex/values").GenericId<"visaRequirements"> | undefined;
    checklist?: {
        completedAt?: number | undefined;
        item: string;
        isCompleted: boolean;
    }[] | undefined;
    status: "completed" | "pending" | "dismissed" | "sent";
    userId: string;
    createdAt: number;
    updatedAt: number;
    travelDate: number;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    reminderDate: number;
}[]>>;
export declare const getUpcomingReminders: import("convex/server").RegisteredQuery<"public", {
    daysAhead?: number | undefined;
    userId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"userVisaReminders">;
    _creationTime: number;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    sentAt?: number | undefined;
    visaRequirementId?: import("convex/values").GenericId<"visaRequirements"> | undefined;
    checklist?: {
        completedAt?: number | undefined;
        item: string;
        isCompleted: boolean;
    }[] | undefined;
    status: "completed" | "pending" | "dismissed" | "sent";
    userId: string;
    createdAt: number;
    updatedAt: number;
    travelDate: number;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    reminderDate: number;
}[]>>;
export declare const getVisaReminderById: import("convex/server").RegisteredQuery<"public", {
    id: import("convex/values").GenericId<"userVisaReminders">;
}, Promise<{
    _id: import("convex/values").GenericId<"userVisaReminders">;
    _creationTime: number;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    sentAt?: number | undefined;
    visaRequirementId?: import("convex/values").GenericId<"visaRequirements"> | undefined;
    checklist?: {
        completedAt?: number | undefined;
        item: string;
        isCompleted: boolean;
    }[] | undefined;
    status: "completed" | "pending" | "dismissed" | "sent";
    userId: string;
    createdAt: number;
    updatedAt: number;
    travelDate: number;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    reminderDate: number;
} | null>>;
export declare const getRemindersForItinerary: import("convex/server").RegisteredQuery<"public", {
    itineraryId: import("convex/values").GenericId<"itineraries">;
}, Promise<{
    _id: import("convex/values").GenericId<"userVisaReminders">;
    _creationTime: number;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    sentAt?: number | undefined;
    visaRequirementId?: import("convex/values").GenericId<"visaRequirements"> | undefined;
    checklist?: {
        completedAt?: number | undefined;
        item: string;
        isCompleted: boolean;
    }[] | undefined;
    status: "completed" | "pending" | "dismissed" | "sent";
    userId: string;
    createdAt: number;
    updatedAt: number;
    travelDate: number;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    reminderDate: number;
}[]>>;
export declare const createVisaReminder: import("convex/server").RegisteredMutation<"public", {
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    visaRequirementId?: import("convex/values").GenericId<"visaRequirements"> | undefined;
    checklist?: {
        completedAt?: number | undefined;
        item: string;
        isCompleted: boolean;
    }[] | undefined;
    userId: string;
    travelDate: number;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    reminderDate: number;
}, Promise<import("convex/values").GenericId<"userVisaReminders">>>;
export declare const updateVisaReminderStatus: import("convex/server").RegisteredMutation<"public", {
    sentAt?: number | undefined;
    status: "completed" | "pending" | "dismissed" | "sent";
    id: import("convex/values").GenericId<"userVisaReminders">;
}, Promise<{
    _id: import("convex/values").GenericId<"userVisaReminders">;
    _creationTime: number;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    sentAt?: number | undefined;
    visaRequirementId?: import("convex/values").GenericId<"visaRequirements"> | undefined;
    checklist?: {
        completedAt?: number | undefined;
        item: string;
        isCompleted: boolean;
    }[] | undefined;
    status: "completed" | "pending" | "dismissed" | "sent";
    userId: string;
    createdAt: number;
    updatedAt: number;
    travelDate: number;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    reminderDate: number;
} | null>>;
export declare const updateVisaReminderChecklist: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"userVisaReminders">;
    checklist: {
        completedAt?: number | undefined;
        item: string;
        isCompleted: boolean;
    }[];
}, Promise<{
    _id: import("convex/values").GenericId<"userVisaReminders">;
    _creationTime: number;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    sentAt?: number | undefined;
    visaRequirementId?: import("convex/values").GenericId<"visaRequirements"> | undefined;
    checklist?: {
        completedAt?: number | undefined;
        item: string;
        isCompleted: boolean;
    }[] | undefined;
    status: "completed" | "pending" | "dismissed" | "sent";
    userId: string;
    createdAt: number;
    updatedAt: number;
    travelDate: number;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    reminderDate: number;
} | null>>;
export declare const deleteVisaReminder: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"userVisaReminders">;
}, Promise<void>>;
export declare const getUserVisaApplications: import("convex/server").RegisteredQuery<"public", {
    status?: "approved" | "rejected" | "cancelled" | "processing" | "submitted" | "preparing" | undefined;
    limit?: number | undefined;
    userId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"visaApplications">;
    _creationTime: number;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    validFrom?: number | undefined;
    validUntil?: number | undefined;
    rejectionReason?: string | undefined;
    documents?: {
        notes?: string | undefined;
        status: "completed" | "not_started" | "in_progress";
        name: string;
    }[] | undefined;
    visaRequirementId?: import("convex/values").GenericId<"visaRequirements"> | undefined;
    applicationDate?: number | undefined;
    expectedResultDate?: number | undefined;
    resultDate?: number | undefined;
    applicationNumber?: string | undefined;
    visaNumber?: string | undefined;
    status: "approved" | "rejected" | "cancelled" | "processing" | "submitted" | "preparing";
    userId: string;
    createdAt: number;
    updatedAt: number;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    applicationMethod: "online" | "embassy" | "consulate" | "visa_center" | "on_arrival";
    plannedTravelDate: number;
}[]>>;
export declare const createVisaApplication: import("convex/server").RegisteredMutation<"public", {
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    documents?: {
        notes?: string | undefined;
        status: "completed" | "not_started" | "in_progress";
        name: string;
    }[] | undefined;
    visaRequirementId?: import("convex/values").GenericId<"visaRequirements"> | undefined;
    applicationDate?: number | undefined;
    expectedResultDate?: number | undefined;
    applicationNumber?: string | undefined;
    userId: string;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    applicationMethod: "online" | "embassy" | "consulate" | "visa_center" | "on_arrival";
    plannedTravelDate: number;
}, Promise<import("convex/values").GenericId<"visaApplications">>>;
export declare const updateVisaApplication: import("convex/server").RegisteredMutation<"public", {
    status?: "approved" | "rejected" | "cancelled" | "processing" | "submitted" | "preparing" | undefined;
    notes?: string | undefined;
    validFrom?: number | undefined;
    validUntil?: number | undefined;
    rejectionReason?: string | undefined;
    documents?: {
        notes?: string | undefined;
        status: "completed" | "not_started" | "in_progress";
        name: string;
    }[] | undefined;
    applicationDate?: number | undefined;
    expectedResultDate?: number | undefined;
    resultDate?: number | undefined;
    applicationNumber?: string | undefined;
    visaNumber?: string | undefined;
    id: import("convex/values").GenericId<"visaApplications">;
}, Promise<{
    _id: import("convex/values").GenericId<"visaApplications">;
    _creationTime: number;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    validFrom?: number | undefined;
    validUntil?: number | undefined;
    rejectionReason?: string | undefined;
    documents?: {
        notes?: string | undefined;
        status: "completed" | "not_started" | "in_progress";
        name: string;
    }[] | undefined;
    visaRequirementId?: import("convex/values").GenericId<"visaRequirements"> | undefined;
    applicationDate?: number | undefined;
    expectedResultDate?: number | undefined;
    resultDate?: number | undefined;
    applicationNumber?: string | undefined;
    visaNumber?: string | undefined;
    status: "approved" | "rejected" | "cancelled" | "processing" | "submitted" | "preparing";
    userId: string;
    createdAt: number;
    updatedAt: number;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    applicationMethod: "online" | "embassy" | "consulate" | "visa_center" | "on_arrival";
    plannedTravelDate: number;
} | null>>;
export declare const deleteVisaApplication: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"visaApplications">;
}, Promise<void>>;
export declare const getVisaApplicationById: import("convex/server").RegisteredQuery<"public", {
    id: import("convex/values").GenericId<"visaApplications">;
}, Promise<{
    _id: import("convex/values").GenericId<"visaApplications">;
    _creationTime: number;
    notes?: string | undefined;
    itineraryId?: import("convex/values").GenericId<"itineraries"> | undefined;
    validFrom?: number | undefined;
    validUntil?: number | undefined;
    rejectionReason?: string | undefined;
    documents?: {
        notes?: string | undefined;
        status: "completed" | "not_started" | "in_progress";
        name: string;
    }[] | undefined;
    visaRequirementId?: import("convex/values").GenericId<"visaRequirements"> | undefined;
    applicationDate?: number | undefined;
    expectedResultDate?: number | undefined;
    resultDate?: number | undefined;
    applicationNumber?: string | undefined;
    visaNumber?: string | undefined;
    status: "approved" | "rejected" | "cancelled" | "processing" | "submitted" | "preparing";
    userId: string;
    createdAt: number;
    updatedAt: number;
    destinationCountryCode: string;
    destinationCountryName: string;
    visaType: "visa_free" | "visa_on_arrival" | "e_visa" | "standard_visa" | "transit_visa" | "work_visa" | "student_visa" | "business_visa";
    applicationMethod: "online" | "embassy" | "consulate" | "visa_center" | "on_arrival";
    plannedTravelDate: number;
} | null>>;
