export declare const list: import("convex/server").RegisteredQuery<"public", {
    type?: "public" | "restaurant" | "hotel" | "other" | "cafe" | "airport" | "train_station" | "shopping_mall" | "library" | "coworking" | undefined;
    limit?: number | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
}, Promise<{
    _id: import("convex/values").GenericId<"wifiSpots">;
    _creationTime: number;
    description?: string | undefined;
    imageUrls?: string[] | undefined;
    nameEn?: string | undefined;
    address?: string | undefined;
    poiId?: import("convex/values").GenericId<"pois"> | undefined;
    openingHours?: string | undefined;
    verifiedAt?: number | undefined;
    verifiedBy?: string | undefined;
    ssid?: string | undefined;
    speedMbps?: number | undefined;
    createdAt: number;
    name: string;
    type: "public" | "restaurant" | "hotel" | "other" | "cafe" | "airport" | "train_station" | "shopping_mall" | "library" | "coworking";
    latitude: number;
    longitude: number;
    updatedAt: number;
    cityId: import("convex/values").GenericId<"cities">;
    ratingCount: number;
    isVerified: boolean;
    requiresPassword: boolean;
    isFree: boolean;
    averageRating: number;
    submittedBy: string;
}[]>>;
export declare const getById: import("convex/server").RegisteredQuery<"public", {
    id: import("convex/values").GenericId<"wifiSpots">;
}, Promise<{
    _id: import("convex/values").GenericId<"wifiSpots">;
    _creationTime: number;
    description?: string | undefined;
    imageUrls?: string[] | undefined;
    nameEn?: string | undefined;
    address?: string | undefined;
    poiId?: import("convex/values").GenericId<"pois"> | undefined;
    openingHours?: string | undefined;
    verifiedAt?: number | undefined;
    verifiedBy?: string | undefined;
    ssid?: string | undefined;
    speedMbps?: number | undefined;
    createdAt: number;
    name: string;
    type: "public" | "restaurant" | "hotel" | "other" | "cafe" | "airport" | "train_station" | "shopping_mall" | "library" | "coworking";
    latitude: number;
    longitude: number;
    updatedAt: number;
    cityId: import("convex/values").GenericId<"cities">;
    ratingCount: number;
    isVerified: boolean;
    requiresPassword: boolean;
    isFree: boolean;
    averageRating: number;
    submittedBy: string;
} | null>>;
export declare const getNearby: import("convex/server").RegisteredQuery<"public", {
    type?: "public" | "restaurant" | "hotel" | "other" | "cafe" | "airport" | "train_station" | "shopping_mall" | "library" | "coworking" | undefined;
    limit?: number | undefined;
    latitude: number;
    longitude: number;
    radiusKm: number;
}, Promise<{
    distance: number;
    _id: import("convex/values").GenericId<"wifiSpots">;
    _creationTime: number;
    description?: string | undefined;
    imageUrls?: string[] | undefined;
    nameEn?: string | undefined;
    address?: string | undefined;
    poiId?: import("convex/values").GenericId<"pois"> | undefined;
    openingHours?: string | undefined;
    verifiedAt?: number | undefined;
    verifiedBy?: string | undefined;
    ssid?: string | undefined;
    speedMbps?: number | undefined;
    createdAt: number;
    name: string;
    type: "public" | "restaurant" | "hotel" | "other" | "cafe" | "airport" | "train_station" | "shopping_mall" | "library" | "coworking";
    latitude: number;
    longitude: number;
    updatedAt: number;
    cityId: import("convex/values").GenericId<"cities">;
    ratingCount: number;
    isVerified: boolean;
    requiresPassword: boolean;
    isFree: boolean;
    averageRating: number;
    submittedBy: string;
}[]>>;
export declare const search: import("convex/server").RegisteredQuery<"public", {
    type?: "public" | "restaurant" | "hotel" | "other" | "cafe" | "airport" | "train_station" | "shopping_mall" | "library" | "coworking" | undefined;
    limit?: number | undefined;
    cityId?: import("convex/values").GenericId<"cities"> | undefined;
    query: string;
}, Promise<{
    _id: import("convex/values").GenericId<"wifiSpots">;
    _creationTime: number;
    description?: string | undefined;
    imageUrls?: string[] | undefined;
    nameEn?: string | undefined;
    address?: string | undefined;
    poiId?: import("convex/values").GenericId<"pois"> | undefined;
    openingHours?: string | undefined;
    verifiedAt?: number | undefined;
    verifiedBy?: string | undefined;
    ssid?: string | undefined;
    speedMbps?: number | undefined;
    createdAt: number;
    name: string;
    type: "public" | "restaurant" | "hotel" | "other" | "cafe" | "airport" | "train_station" | "shopping_mall" | "library" | "coworking";
    latitude: number;
    longitude: number;
    updatedAt: number;
    cityId: import("convex/values").GenericId<"cities">;
    ratingCount: number;
    isVerified: boolean;
    requiresPassword: boolean;
    isFree: boolean;
    averageRating: number;
    submittedBy: string;
}[]>>;
export declare const create: import("convex/server").RegisteredMutation<"public", {
    description?: string | undefined;
    imageUrls?: string[] | undefined;
    nameEn?: string | undefined;
    address?: string | undefined;
    poiId?: import("convex/values").GenericId<"pois"> | undefined;
    openingHours?: string | undefined;
    ssid?: string | undefined;
    speedMbps?: number | undefined;
    name: string;
    type: "public" | "restaurant" | "hotel" | "other" | "cafe" | "airport" | "train_station" | "shopping_mall" | "library" | "coworking";
    latitude: number;
    longitude: number;
    cityId: import("convex/values").GenericId<"cities">;
    requiresPassword: boolean;
    isFree: boolean;
    submittedBy: string;
}, Promise<import("convex/values").GenericId<"wifiSpots">>>;
export declare const update: import("convex/server").RegisteredMutation<"public", {
    name?: string | undefined;
    type?: "public" | "restaurant" | "hotel" | "other" | "cafe" | "airport" | "train_station" | "shopping_mall" | "library" | "coworking" | undefined;
    description?: string | undefined;
    imageUrls?: string[] | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    nameEn?: string | undefined;
    address?: string | undefined;
    openingHours?: string | undefined;
    ssid?: string | undefined;
    requiresPassword?: boolean | undefined;
    isFree?: boolean | undefined;
    speedMbps?: number | undefined;
    id: import("convex/values").GenericId<"wifiSpots">;
}, Promise<{
    _id: import("convex/values").GenericId<"wifiSpots">;
    _creationTime: number;
    description?: string | undefined;
    imageUrls?: string[] | undefined;
    nameEn?: string | undefined;
    address?: string | undefined;
    poiId?: import("convex/values").GenericId<"pois"> | undefined;
    openingHours?: string | undefined;
    verifiedAt?: number | undefined;
    verifiedBy?: string | undefined;
    ssid?: string | undefined;
    speedMbps?: number | undefined;
    createdAt: number;
    name: string;
    type: "public" | "restaurant" | "hotel" | "other" | "cafe" | "airport" | "train_station" | "shopping_mall" | "library" | "coworking";
    latitude: number;
    longitude: number;
    updatedAt: number;
    cityId: import("convex/values").GenericId<"cities">;
    ratingCount: number;
    isVerified: boolean;
    requiresPassword: boolean;
    isFree: boolean;
    averageRating: number;
    submittedBy: string;
} | null>>;
export declare const verify: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"wifiSpots">;
    verifiedBy: string;
}, Promise<{
    _id: import("convex/values").GenericId<"wifiSpots">;
    _creationTime: number;
    description?: string | undefined;
    imageUrls?: string[] | undefined;
    nameEn?: string | undefined;
    address?: string | undefined;
    poiId?: import("convex/values").GenericId<"pois"> | undefined;
    openingHours?: string | undefined;
    verifiedAt?: number | undefined;
    verifiedBy?: string | undefined;
    ssid?: string | undefined;
    speedMbps?: number | undefined;
    createdAt: number;
    name: string;
    type: "public" | "restaurant" | "hotel" | "other" | "cafe" | "airport" | "train_station" | "shopping_mall" | "library" | "coworking";
    latitude: number;
    longitude: number;
    updatedAt: number;
    cityId: import("convex/values").GenericId<"cities">;
    ratingCount: number;
    isVerified: boolean;
    requiresPassword: boolean;
    isFree: boolean;
    averageRating: number;
    submittedBy: string;
} | null>>;
export declare const remove: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"wifiSpots">;
}, Promise<void>>;
export declare const updateRating: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"wifiSpots">;
    ratingCount: number;
    averageRating: number;
}, Promise<{
    _id: import("convex/values").GenericId<"wifiSpots">;
    _creationTime: number;
    description?: string | undefined;
    imageUrls?: string[] | undefined;
    nameEn?: string | undefined;
    address?: string | undefined;
    poiId?: import("convex/values").GenericId<"pois"> | undefined;
    openingHours?: string | undefined;
    verifiedAt?: number | undefined;
    verifiedBy?: string | undefined;
    ssid?: string | undefined;
    speedMbps?: number | undefined;
    createdAt: number;
    name: string;
    type: "public" | "restaurant" | "hotel" | "other" | "cafe" | "airport" | "train_station" | "shopping_mall" | "library" | "coworking";
    latitude: number;
    longitude: number;
    updatedAt: number;
    cityId: import("convex/values").GenericId<"cities">;
    ratingCount: number;
    isVerified: boolean;
    requiresPassword: boolean;
    isFree: boolean;
    averageRating: number;
    submittedBy: string;
} | null>>;
