/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 *
 * Consider adding this file to .prettierignore and eslint ignore.
 */

declare module 'motia' {
  interface FlowContextStateStreams {}

  interface Handlers {}
}
