import Foundation

// MARK: - AI Plan Request Models

/// Request to start AI travel planning
struct AIPlanStartRequest: Encodable {
    let sessionId: String
    let message: String
    let userId: String?
}

/// Request to provide feedback to AI planner
struct AIPlanFeedbackRequest: Encodable {
    let feedback: String
}

// MARK: - AI Plan Response Models

/// Response from starting a planning session
struct AIPlanStartResponse: Codable {
    let success: Bool
    let sessionId: String
    let response: String
    var plan: AIPlanDraft?
    let waitingForFeedback: Bool
}

/// Response from providing feedback
struct AIPlanFeedbackResponse: Codable {
    let success: Bool
    let sessionId: String
    let response: String
    var plan: AIPlanDraft?
    let completed: Bool
}

/// Response from checking session status
struct AIPlanStatusResponse: Codable {
    let success: Bool
    let sessionId: String
    let currentStep: String
    let destination: String?
    let duration: Int?
    let hasDraftPlan: Bool
    let hasFinalPlan: Bool
    let waitingForFeedback: Bool
}

/// Response from getting final plan
struct AIPlanResultResponse: Codable {
    let success: Bool
    let sessionId: String
    var plan: AIPlanDraft
    let completed: Bool
}

// MARK: - AI Plan Models

/// Draft travel plan generated by AI
struct AIPlanDraft: Codable, Identifiable {
    var id: String { sessionId }
    var sessionId: String
    let title: String
    let summary: String
    let days: [AIPlanDay]
    let estimatedBudget: String?
    let packingList: [String]?
    let tips: [String]?

    enum CodingKeys: String, CodingKey {
        case sessionId
        case title
        case summary
        case days
        case estimatedBudget
        case packingList
        case tips
    }

    init(sessionId: String = UUID().uuidString, title: String, summary: String, days: [AIPlanDay], estimatedBudget: String? = nil, packingList: [String]? = nil, tips: [String]? = nil) {
        self.sessionId = sessionId
        self.title = title
        self.summary = summary
        self.days = days
        self.estimatedBudget = estimatedBudget
        self.packingList = packingList
        self.tips = tips
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        // sessionId might not be in the plan JSON, so we'll add it later
        self.sessionId = (try? container.decode(String.self, forKey: .sessionId)) ?? UUID().uuidString
        self.title = try container.decode(String.self, forKey: .title)
        self.summary = try container.decode(String.self, forKey: .summary)
        self.days = try container.decode([AIPlanDay].self, forKey: .days)
        self.estimatedBudget = try? container.decode(String.self, forKey: .estimatedBudget)
        self.packingList = try? container.decode([String].self, forKey: .packingList)
        self.tips = try? container.decode([String].self, forKey: .tips)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sessionId, forKey: .sessionId)
        try container.encode(title, forKey: .title)
        try container.encode(summary, forKey: .summary)
        try container.encode(days, forKey: .days)
        try container.encodeIfPresent(estimatedBudget, forKey: .estimatedBudget)
        try container.encodeIfPresent(packingList, forKey: .packingList)
        try container.encodeIfPresent(tips, forKey: .tips)
    }
}

/// A day in the AI-generated plan
struct AIPlanDay: Codable, Identifiable {
    let id: String
    let dayNumber: Int
    let theme: String?
    let activities: [AIPlanActivity]

    enum CodingKeys: String, CodingKey {
        case dayNumber
        case theme
        case activities
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.dayNumber = try container.decode(Int.self, forKey: .dayNumber)
        self.theme = try? container.decode(String.self, forKey: .theme)
        self.activities = try container.decode([AIPlanActivity].self, forKey: .activities)
        self.id = UUID().uuidString
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(dayNumber, forKey: .dayNumber)
        try container.encodeIfPresent(theme, forKey: .theme)
        try container.encode(activities, forKey: .activities)
    }
}

/// An activity in the AI-generated plan
struct AIPlanActivity: Codable, Identifiable {
    let id: String
    let time: String
    let name: String
    let type: String
    let duration: String?
    let description: String?
    let tips: String?
    let transportToNext: AIPlanTransport?

    enum CodingKeys: String, CodingKey {
        case time
        case name
        case type
        case duration
        case description
        case tips
        case transportToNext
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.time = try container.decode(String.self, forKey: .time)
        self.name = try container.decode(String.self, forKey: .name)
        self.type = try container.decode(String.self, forKey: .type)
        self.duration = try? container.decode(String.self, forKey: .duration)
        self.description = try? container.decode(String.self, forKey: .description)
        self.tips = try? container.decode(String.self, forKey: .tips)
        self.transportToNext = try? container.decode(AIPlanTransport.self, forKey: .transportToNext)
        self.id = UUID().uuidString
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(time, forKey: .time)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(tips, forKey: .tips)
        try container.encodeIfPresent(transportToNext, forKey: .transportToNext)
    }
}

/// Transport information between activities
struct AIPlanTransport: Codable {
    let mode: String
    let note: String?
}

// MARK: - Conversion to SavedItinerary

extension AIPlanDraft {
    /// Convert AI plan to SavedItinerary for importing
    func toSavedItinerary(destination: String?) -> SavedItinerary {
        let aiDays = days.map { planDay in
            AiDay(
                dayNumber: planDay.dayNumber,
                theme: planDay.theme,
                pois: planDay.activities.map { activity in
                    var poi = AiPoi(name: activity.name)
                    poi.type = activity.type
                    poi.description = activity.description
                    poi.time = activity.time
                    poi.duration = activity.duration
                    poi.tips = activity.tips
                    return poi
                }
            )
        }

        // Use the title/destination init and manually set properties
        var itinerary = SavedItinerary(
            id: UUID(),
            title: title,
            destination: destination,
            daysCount: days.count
        )
        itinerary.days = aiDays
        return itinerary
    }
}
